// TEIL 2 — "Datenstrukturen & Robustheit" (siehe MASTERPROMPT Abschnitt 9)
export default {
  id: "teil2",
  nummer: 2,
  titel: "Datenstrukturen & Robustheit",
  untertitel: "Programme, die echte Daten überleben",
  farbe: "var(--violet)",
  voraussetzung: "teil1",
  lektionen: [
    {
      id: "t2l1",
      titel: "Dictionaries",
      icon: "🗝",
      farbe: "var(--violet)",
      kurz: "Daten mit Namen statt Nummern.",
      slides: [
        {
          h: "Was ist ein Dictionary?",
          p: "Ein <code>dict</code> speichert Werte unter einem Schlüssel (key) statt unter einem Index.",
          code: 'person = {"name": "Simon", "alter": 21}\nprint(person["name"])',
        },
        {
          h: ".get() nutzen",
          p: "<code>.get()</code> gibt None statt eines Fehlers zurück, wenn der Schlüssel fehlt.",
          code: 'print(person.get("stadt"))',
        },
        {
          h: "in prüfen",
          p: "Mit <code>in</code> prüfst du, ob ein Schlüssel existiert.",
          code: 'print("alter" in person)',
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Wie greifst du auf den Wert zu 'name' zu?",
          code: 'person = {"name": "Simon"}',
          opts: ["person[0]", 'person["name"]', "person.name", "person(name)"],
          a: 1,
          ex: "Dictionaries werden über den Schlüssel in eckigen Klammern angesprochen.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: 'd = {"a": 1}\nprint(d.get("b"))',
          accept: ["None"],
          ex: ".get() gibt None zurück, wenn der Schlüssel fehlt, statt einen Fehler zu werfen.",
        },
        {
          t: "fill",
          q: "Vervollständige: prüfe ob 'x' ein Schlüssel in d ist.",
          code: '"x" ___ d',
          accept: ["in"],
          ex: "Der in-Operator prüft die Schlüssel eines Dictionaries.",
        },
        {
          t: "mc",
          q: "Was passiert bei d['fehlt'], wenn der Schlüssel nicht existiert?",
          code: 'd = {"a": 1}\nd["fehlt"]',
          opts: ["None", "0", "KeyError", "leerer String"],
          a: 2,
          ex: "Eckige Klammern werfen einen KeyError bei fehlendem Schlüssel — .get() nicht.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: 'd = {"a": 1}\nd["b"] = 2\nprint(d["b"])',
          accept: ["2"],
          ex: "Zuweisung an einen neuen Schlüssel fügt ihn dem Dictionary hinzu.",
        },
        {
          t: "build",
          q: "Erstelle ein Dictionary 'buch' mit den Schlüsseln 'titel' und 'autor' und gib beide Werte aus.",
          starter: "",
          check: { stdout: ["Dune", "Frank Herbert"] },
          hints: ["Ein dict wird mit {} erstellt.", "Zugriff über eckige Klammern.", 'buch = {"titel": "Dune", "autor": "Frank Herbert"}\nprint(buch["titel"])\nprint(buch["autor"])'],
          loesung: 'buch = {"titel": "Dune", "autor": "Frank Herbert"}\nprint(buch["titel"])\nprint(buch["autor"])',
          ex: "Dictionaries bündeln zusammengehörige Werte unter sprechenden Namen.",
        },
        {
          t: "build",
          q: "Nutze .get() um nach einem nicht existierenden Schlüssel 'isbn' zu fragen und gib das Ergebnis aus.",
          starter: 'buch = {"titel": "Dune"}\n',
          check: { stdout: ["None"] },
          hints: [".get() gibt None zurück statt zu crashen.", "print(buch.get(...))", 'print(buch.get("isbn"))'],
          loesung: 'buch = {"titel": "Dune"}\nprint(buch.get("isbn"))',
          ex: ".get() ist die robuste Art, unsichere Zugriffe zu machen.",
        },
        {
          t: "build",
          q: "Füge dem Dictionary 'buch' den Schlüssel 'jahr' mit Wert 1965 hinzu und gib das ganze dict aus.",
          starter: 'buch = {"titel": "Dune"}\n',
          check: { stdout: ["{'titel': 'Dune', 'jahr': 1965}"] },
          hints: ["Zuweisung an einen neuen Schlüssel erstellt ihn.", 'buch["jahr"] = 1965', 'buch["jahr"] = 1965\nprint(buch)'],
          loesung: 'buch = {"titel": "Dune"}\nbuch["jahr"] = 1965\nprint(buch)',
          ex: "Dictionaries sind veränderlich — neue Schlüssel lassen sich jederzeit ergänzen.",
        },
        {
          t: "build",
          q: "Prüfe mit 'in', ob 'autor' ein Schlüssel in 'buch' ist, und gib das Ergebnis aus.",
          starter: 'buch = {"titel": "Dune"}\n',
          check: { stdout: ["False"] },
          hints: ["in prüft die Schlüssel, nicht die Werte.", "Nutze print(...) mit dem in-Ausdruck.", 'print("autor" in buch)'],
          loesung: 'buch = {"titel": "Dune"}\nprint("autor" in buch)',
          ex: "in ist der sichere Weg, Existenz zu prüfen, bevor man zugreift.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Funktionen. Schreibe eine Funktion 'zeig_titel(buch)', die den Titel ausgibt, falls vorhanden, sonst 'Kein Titel'.",
          starter: "",
          check: {
            stdout: ["Dune", "Kein Titel"],
            tests: 'zeig_titel({"titel": "Dune"})\nzeig_titel({})',
          },
          hints: ["Nutze .get() mit einem Standardwert.", "def zeig_titel(buch): print(buch.get('titel', 'Kein Titel'))", 'def zeig_titel(buch):\n    print(buch.get("titel", "Kein Titel"))'],
          loesung: 'def zeig_titel(buch):\n    print(buch.get("titel", "Kein Titel"))',
          ex: ".get() mit zweitem Argument liefert einen Standardwert statt None.",
        },
      ],
      lernlog: [
        "Dictionaries speichern Werte unter Schlüsseln",
        "Zugriff über eckige Klammern kann KeyError werfen",
        ".get() gibt None oder einen Standardwert zurück",
        "in prüft, ob ein Schlüssel existiert",
        "Neue Schlüssel werden per Zuweisung ergänzt",
      ],
    },
    {
      id: "t2l2",
      titel: "Dictionaries II & Verschachtelung",
      icon: "🗂",
      farbe: "var(--cyan)",
      kurz: "Ganze Datensätze in einer Struktur.",
      slides: [
        {
          h: "Über Dictionaries iterieren",
          p: "Mit <code>.items()</code> bekommst du bei jedem Schleifendurchlauf ein Schlüssel-Wert-Paar auf einmal. <code>.keys()</code> und <code>.values()</code> geben nur die Schlüssel bzw. nur die Werte zurück. Das ist der Standardweg, ein ganzes dict zu durchlaufen.",
          code: 'preise = {"apfel": 0.5, "brot": 2.2}\nfor name, preis in preise.items():\n    print(name, preis)',
        },
        {
          h: "Verschachtelte Dictionaries",
          p: "Ein Wert in einem dict kann selbst wieder ein dict sein — so bildest du strukturierte Daten ab, etwa eine Person mit mehreren Eigenschaften. Der Zugriff verkettet sich einfach: <code>d[\"a\"][\"b\"]</code>.",
          code: 'person = {"name": "Anna", "adresse": {"stadt": "Berlin", "plz": "10115"}}\nprint(person["adresse"]["stadt"])',
        },
        {
          h: "Listen von Dictionaries",
          p: "Eine Liste voller gleich aufgebauter dicts ist wie eine Mini-Datenbank: jedes dict ist ein Datensatz. Mit einer Schleife durchsuchst oder wertest du alle Einträge aus.",
          code: 'kunden = [{"name": "Anna", "alter": 23}, {"name": "Ben", "alter": 31}]\nfor kunde in kunden:\n    print(kunde["name"])',
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Was gibt 'for k in d:' bei einem dict d aus (ohne .items())?",
          code: "",
          opts: ["Nur die Werte", "Nur die Schlüssel", "Schlüssel-Wert-Paare als Tupel", "Einen Fehler"],
          a: 1,
          ex: "Ohne .items() iteriert eine for-Schleife über ein dict automatisch über dessen Schlüssel.",
        },
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: 'preise = {"apfel": 1}\nfor name, preis in preise.items():\n    print(name, preis)',
          accept: ["apfel 1"],
          ex: ".items() liefert bei jedem Durchlauf ein (Schlüssel, Wert)-Paar, das du direkt entpacken kannst.",
        },
        {
          t: "fill",
          q: "Vervollständige: iteriere über Schlüssel UND Werte von d.",
          code: "for k, v in d.___():\n    print(k, v)",
          accept: ["items"],
          ex: ".items() ist die Methode, die Schlüssel und Wert zusammen liefert.",
        },
        {
          t: "mc",
          q: 'Wie greifst du bei person = {"adresse": {"stadt": "Berlin"}} auf "Berlin" zu?',
          code: "",
          opts: ['person["stadt"]', 'person["adresse"]["stadt"]', 'person["adresse"].stadt', 'person.adresse["stadt"]'],
          a: 1,
          ex: "Verschachtelte Zugriffe werden einfach hintereinander in eckigen Klammern verkettet.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: 'kunden = [{"name": "Anna"}, {"name": "Ben"}]\nprint(kunden[1]["name"])',
          accept: ["Ben"],
          ex: "Erst der Listenindex wählt das dict aus, dann der Schlüssel den Wert darin.",
        },
        {
          t: "build",
          q: "Gib mit .items() jeden Schlüssel und Wert von 'preise' auf einer eigenen Zeile aus (Format: 'name preis').",
          starter: 'preise = {"apfel": 1, "brot": 2}\n',
          check: { stdout: ["apfel 1", "brot 2"] },
          hints: ["Nutze eine for-Schleife über .items().", "for name, preis in preise.items():", 'for name, preis in preise.items():\n    print(name, preis)'],
          loesung: 'preise = {"apfel": 1, "brot": 2}\nfor name, preis in preise.items():\n    print(name, preis)',
          ex: ".items() ist der direkte Weg, Schlüssel und Wert gemeinsam zu verarbeiten.",
        },
        {
          t: "build",
          q: "Erstelle ein verschachteltes dict 'person' mit 'name'='Anna' und 'adresse' als eigenem dict mit 'stadt'='Berlin'. Gib die Stadt aus.",
          starter: "",
          check: { stdout: ["Berlin"] },
          hints: ["Ein Wert im dict kann selbst ein dict sein.", 'person = {"name": "Anna", "adresse": {"stadt": "Berlin"}}', 'person = {"name": "Anna", "adresse": {"stadt": "Berlin"}}\nprint(person["adresse"]["stadt"])'],
          loesung: 'person = {"name": "Anna", "adresse": {"stadt": "Berlin"}}\nprint(person["adresse"]["stadt"])',
          ex: "Verschachtelte dicts bilden reale, strukturierte Daten ab — ein Zugriffspfad pro Ebene.",
        },
        {
          t: "build",
          q: "Gegeben eine Liste von Kunden-dicts. Gib mit einer Schleife den Namen jedes Kunden aus.",
          starter: 'kunden = [{"name": "Anna"}, {"name": "Ben"}, {"name": "Cem"}]\n',
          check: { stdout: ["Anna", "Ben", "Cem"] },
          hints: ["Iteriere über die Liste mit einer for-Schleife.", "for kunde in kunden:", 'for kunde in kunden:\n    print(kunde["name"])'],
          loesung: 'kunden = [{"name": "Anna"}, {"name": "Ben"}, {"name": "Cem"}]\nfor kunde in kunden:\n    print(kunde["name"])',
          ex: "Eine Liste von dicts ist wie eine Tabelle — jede Zeile ein dict, jede Spalte ein Schlüssel.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion 'gesamtpreis(warenkorb)', die eine Liste von Produkt-dicts (mit Schlüssel 'preis') entgegennimmt und die Summe aller Preise zurückgibt.",
          starter: "",
          check: { tests: 'assert gesamtpreis([{"preis": 2}, {"preis": 3}]) == 5\nassert gesamtpreis([]) == 0' },
          hints: ["Nutze eine Schleife und eine Summenvariable.", 'summe = 0\nfor p in warenkorb:\n    summe += p["preis"]', 'def gesamtpreis(warenkorb):\n    summe = 0\n    for p in warenkorb:\n        summe += p["preis"]\n    return summe'],
          loesung: 'def gesamtpreis(warenkorb):\n    summe = 0\n    for p in warenkorb:\n        summe += p["preis"]\n    return summe',
          ex: "Listen von dicts + Schleife + Akkumulator-Muster — die Basis für jede Datenauswertung.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: .get() aus t2l1. Schreibe eine Funktion 'durchschnittsalter(personen)', die eine Liste von Personen-dicts entgegennimmt (manche haben den Schlüssel 'alter', manche nicht) und den Durchschnitt der vorhandenen Altersangaben zurückgibt. Fehlende Angaben werden ignoriert.",
          starter: "",
          check: {
            tests: 'assert durchschnittsalter([{"alter": 20}, {"alter": 30}, {"name": "x"}]) == 25.0\nassert durchschnittsalter([{"name": "x"}]) == 0',
          },
          hints: [
            "Nutze .get(), um fehlende Werte sicher zu behandeln.",
            "Zähle mit, wie viele gültige Altersangaben du gefunden hast.",
            'alter = p.get("alter")\nif alter is not None:\n    summe += alter\n    anzahl += 1',
          ],
          loesung: 'def durchschnittsalter(personen):\n    summe = 0\n    anzahl = 0\n    for p in personen:\n        alter = p.get("alter")\n        if alter is not None:\n            summe += alter\n            anzahl += 1\n    return summe / anzahl if anzahl > 0 else 0',
          ex: "Kombination aus robustem Zugriff (.get()) und Aggregation über eine Liste von dicts — typisch für echte Datenverarbeitung.",
        },
      ],
      lernlog: [
        "items() liefert Schlüssel und Wert gemeinsam",
        "for k in d iteriert standardmäßig über die Schlüssel",
        "Werte in einem dict können selbst dicts sein",
        'Verschachtelte Zugriffe werden verkettet: d["a"]["b"]',
        "Listen von dicts bilden Mini-Datenbanken ab",
        "Schleife + Akkumulator wertet Listen von dicts aus",
      ],
    },
    {
      id: "t2l3",
      titel: "Tuples & Sets",
      icon: "📦",
      farbe: "var(--magenta)",
      kurz: "Fixe Werte und Mengen ohne Duplikate.",
      slides: [
        {
          h: "Tuples — unveränderliche Listen",
          p: "Ein <code>tuple</code> sieht aus wie eine Liste, wird aber mit runden Klammern geschrieben und lässt sich nach der Erstellung nicht mehr ändern. Das eignet sich für Werte, die zusammengehören und fix bleiben sollen, etwa Koordinaten.",
          code: 'punkt = (3, 4)\nprint(punkt[0])\n# punkt[0] = 9 wuerde TypeError werfen',
        },
        {
          h: "Tuples entpacken",
          p: "Ein Tuple lässt sich direkt in mehrere Variablen entpacken — das kennst du schon von .items(). Die Anzahl der Variablen muss zur Anzahl der Werte passen.",
          code: "x, y = punkt\nprint(x, y)",
        },
        {
          h: "Sets — Mengen ohne Duplikate",
          p: "Ein <code>set</code> speichert Werte ohne feste Reihenfolge und ohne Duplikate — ideal, um doppelte Einträge zu entfernen. Mit <code>&</code>, <code>|</code> und <code>-</code> rechnest du wie mit Mengen in der Mathematik: Schnitt, Vereinigung, Differenz.",
          code: "zahlen = [1, 2, 2, 3, 3, 3]\neinzigartig = set(zahlen)\nprint(len(einzigartig))",
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Was passiert bei punkt = (1, 2); punkt[0] = 9?",
          code: "",
          opts: ["Funktioniert, punkt wird (9, 2)", "TypeError, weil Tuples unveränderlich sind", "IndexError", "Nichts, der Wert bleibt (1, 2) ohne Fehler"],
          a: 1,
          ex: "Tuples sind immutable — jede Änderung nach der Erstellung wirft einen TypeError.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: "punkt = (5, 10)\nx, y = punkt\nprint(x + y)",
          accept: ["15"],
          ex: "Entpacken weist die Tuple-Werte in der Reihenfolge auf die Variablen zu.",
        },
        {
          t: "fill",
          q: "Vervollständige, um Duplikate aus 'zahlen' zu entfernen.",
          code: "einzigartig = ___(zahlen)",
          accept: ["set"],
          ex: "set() wandelt eine Liste in eine Menge ohne Duplikate um.",
        },
        {
          t: "mc",
          q: "Was gibt len({1, 2, 2, 3}) zurück?",
          code: "",
          opts: ["4", "3", "2", "Fehler"],
          a: 1,
          ex: "Ein set entfernt Duplikate automatisch — aus {1, 2, 2, 3} werden 3 einzigartige Werte.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: "a = {1, 2, 3}\nb = {2, 3, 4}\nprint(sorted(a & b))",
          accept: ["[2, 3]"],
          ex: "& liefert die Schnittmenge; sorted() macht die Ausgabe vorhersehbar, weil sets keine feste Reihenfolge haben.",
        },
        {
          t: "build",
          q: "Erstelle das Tuple 'koordinate' mit den Werten 7 und 2, entpacke es in 'x' und 'y' und gib beide auf einer Zeile aus (print(x, y)).",
          starter: "",
          check: { stdout: ["7 2"] },
          hints: ["Ein Tuple wird mit runden Klammern geschrieben.", "x, y = koordinate", "koordinate = (7, 2)\nx, y = koordinate\nprint(x, y)"],
          loesung: "koordinate = (7, 2)\nx, y = koordinate\nprint(x, y)",
          ex: "Tuple-Entpacken ist der übliche Weg, mehrere zusammengehörige Werte auf einmal zu benennen.",
        },
        {
          t: "build",
          q: "Gegeben eine Liste 'namen' mit Duplikaten. Entferne die Duplikate mit einem set, wandle das Ergebnis mit sorted() in eine sortierte Liste um und gib sie aus.",
          starter: 'namen = ["Anna", "Ben", "Anna", "Cem", "Ben"]\n',
          check: { stdout: ["['Anna', 'Ben', 'Cem']"] },
          hints: ["set(namen) entfernt Duplikate.", "sorted(set(namen)) gibt eine sortierte Liste zurück.", "print(sorted(set(namen)))"],
          loesung: 'namen = ["Anna", "Ben", "Anna", "Cem", "Ben"]\nprint(sorted(set(namen)))',
          ex: "set() + sorted() ist das Standardmuster: Duplikate weg, Ausgabe wieder deterministisch.",
        },
        {
          t: "build",
          q: "Zwei Kurse als sets: 'python_kurs' und 'js_kurs' (Namen von Teilnehmenden). Gib sortiert aus, wer in BEIDEN Kursen ist.",
          starter: 'python_kurs = {"Anna", "Ben", "Cem"}\njs_kurs = {"Ben", "Cem", "Dea"}\n',
          check: { stdout: ["['Ben', 'Cem']"] },
          hints: ["& berechnet die Schnittmenge zweier sets.", "sorted(python_kurs & js_kurs)", "print(sorted(python_kurs & js_kurs))"],
          loesung: 'python_kurs = {"Anna", "Ben", "Cem"}\njs_kurs = {"Ben", "Cem", "Dea"}\nprint(sorted(python_kurs & js_kurs))',
          ex: "Die Schnittmenge (&) beantwortet direkt 'wer ist in beiden' — ohne verschachtelte Schleifen.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion 'entferne_duplikate(liste)', die eine Liste zurückgibt, in der jedes Element nur einmal vorkommt — als sortierte Liste.",
          starter: "",
          check: { tests: "assert entferne_duplikate([3, 1, 2, 1, 3]) == [1, 2, 3]\nassert entferne_duplikate([]) == []" },
          hints: ["Nutze set(), um Duplikate zu entfernen.", "Wandle das Ergebnis mit sorted() in eine Liste um.", "def entferne_duplikate(liste):\n    return sorted(set(liste))"],
          loesung: "def entferne_duplikate(liste):\n    return sorted(set(liste))",
          ex: "set() + sorted() als Funktion verpackt — wiederverwendbares Werkzeug statt Einmal-Code.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Dictionaries aus t2l1. Schreibe eine Funktion 'zaehle_vorkommen(woerter)', die eine Liste von Wörtern entgegennimmt und ein dict zurückgibt, das für jedes einzigartige Wort zählt, wie oft es vorkommt.",
          starter: "",
          check: { tests: 'ergebnis = zaehle_vorkommen(["a", "b", "a", "c", "b", "a"])\nassert ergebnis == {"a": 3, "b": 2, "c": 1}' },
          hints: [
            "Nutze set(woerter), um die einzigartigen Wörter zu bekommen.",
            "Für jedes einzigartige Wort: zähle mit .count() oder einer Schleife, wie oft es vorkommt.",
            'def zaehle_vorkommen(woerter):\n    ergebnis = {}\n    for w in set(woerter):\n        ergebnis[w] = woerter.count(w)\n    return ergebnis',
          ],
          loesung: 'def zaehle_vorkommen(woerter):\n    ergebnis = {}\n    for w in set(woerter):\n        ergebnis[w] = woerter.count(w)\n    return ergebnis',
          ex: "Sets liefern die einzigartigen Kandidaten, dicts sammeln das Ergebnis — zwei Datenstrukturen ergänzen sich.",
        },
      ],
      lernlog: [
        "Tuples werden mit () geschrieben und sind unveränderlich",
        "Tuple-Entpacken weist mehrere Werte auf einmal zu",
        "Sets speichern Werte ohne Duplikate und ohne feste Reihenfolge",
        "set() entfernt Duplikate aus einer Liste",
        "& berechnet die Schnittmenge, | die Vereinigung, - die Differenz",
        "sorted() macht Set-Ausgaben deterministisch",
      ],
    },
    {
      id: "t2l4",
      titel: "Slicing & String-Werkzeuge",
      icon: "✂️",
      farbe: "var(--lime)",
      kurz: "Text und Listen präzise zerlegen.",
      slides: [
        {
          h: "Slicing — Teilstücke herausschneiden",
          p: "Mit <code>[start:stop:step]</code> schneidest du einen Ausschnitt aus einer Liste oder einem String heraus. <code>start</code> ist inklusiv, <code>stop</code> exklusiv — beide Seiten dürfen leer bleiben.",
          code: 'text = "Python"\nprint(text[1:4])\nprint(text[::-1])',
        },
        {
          h: "Strings zerlegen mit .split()",
          p: "<code>.split()</code> zerlegt einen String an einem Trennzeichen in eine Liste von Teilstrings. Ohne Argument wird an beliebigem Whitespace getrennt.",
          code: 'zeile = "Anna,23,Berlin"\nteile = zeile.split(",")\nprint(teile)',
        },
        {
          h: "Strings zusammensetzen und säubern",
          p: "<code>.join()</code> ist das Gegenteil von .split() — es fügt eine Liste zu einem String zusammen. <code>.strip()</code> entfernt Leerzeichen am Rand, <code>.replace()</code> ersetzt Teilstrings.",
          code: 'woerter = ["a", "b", "c"]\nprint("-".join(woerter))\nprint("  hi  ".strip())',
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: 'Was gibt "Python"[1:4] zurück?',
          code: "",
          opts: ["Pyth", "ytho", "yth", "ython"],
          a: 2,
          ex: "Index 1 bis exklusiv 4 sind die Zeichen y, t, h — das ergibt 'yth'.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: 'text = "Hallo"\nprint(text[::-1])',
          accept: ["ollaH"],
          ex: "Ein Schritt von -1 kehrt die Reihenfolge um — ein beliebter Trick zum Umdrehen.",
        },
        {
          t: "fill",
          q: "Vervollständige, um 'a,b,c' in die Liste ['a', 'b', 'c'] zu zerlegen.",
          code: '"a,b,c".___(",")',
          accept: ["split"],
          ex: ".split() trennt einen String an einem Zeichen in eine Liste auf.",
        },
        {
          t: "mc",
          q: 'Was macht "  hi  ".strip()?',
          code: "",
          opts: ["Entfernt alle Leerzeichen im String", "Entfernt nur Leerzeichen am Anfang und Ende", "Ersetzt Leerzeichen durch Unterstriche", "Wirft einen Fehler"],
          a: 1,
          ex: ".strip() entfernt Whitespace nur an den Rändern, nicht innen.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: 'teile = ["2024", "01", "15"]\nprint("-".join(teile))',
          accept: ["2024-01-15"],
          ex: ".join() fügt die Liste zusammen und setzt das Trennzeichen zwischen jedes Element.",
        },
        {
          t: "build",
          q: "Gegeben der String 'satz'. Gib mit Slicing die ersten drei Zeichen aus.",
          starter: 'satz = "Programmieren"\n',
          check: { stdout: ["Pro"] },
          hints: ["Slicing: satz[start:stop].", "satz[0:3] oder satz[:3]", "print(satz[:3])"],
          loesung: 'satz = "Programmieren"\nprint(satz[:3])',
          ex: "Slicing ohne Start bedeutet 'von Anfang an' — knapper Standardstil.",
        },
        {
          t: "build",
          q: "Gegeben eine CSV-artige Zeile 'zeile'. Zerlege sie an Kommas mit .split() und gib jeden Teil auf einer eigenen Zeile aus.",
          starter: 'zeile = "Anna,23,Berlin"\n',
          check: { stdout: ["Anna", "23", "Berlin"] },
          hints: ['.split(",") gibt eine Liste zurück.', "Iteriere über die Liste mit einer for-Schleife.", 'for teil in zeile.split(","):\n    print(teil)'],
          loesung: 'zeile = "Anna,23,Berlin"\nfor teil in zeile.split(","):\n    print(teil)',
          ex: ".split() + Schleife ist das Standardmuster, um strukturierten Text zeilenweise zu verarbeiten.",
        },
        {
          t: "build",
          q: "Gegeben eine Liste von Wörtern 'woerter'. Setze sie mit .join() zu einem einzigen, durch Leerzeichen getrennten Satz zusammen und gib ihn aus.",
          starter: 'woerter = ["Python", "macht", "Spass"]\n',
          check: { stdout: ["Python macht Spass"] },
          hints: [".join() wird auf dem Trennzeichen-String aufgerufen.", '" ".join(woerter)', 'print(" ".join(woerter))'],
          loesung: 'woerter = ["Python", "macht", "Spass"]\nprint(" ".join(woerter))',
          ex: ".join() ist das Gegenstück zu .split() — aus der Liste wird wieder ein String.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion 'saubere_eingabe(text)', die führende/nachfolgende Leerzeichen entfernt und alle verbleibenden Leerzeichen durch Unterstriche ersetzt.",
          starter: "",
          check: { tests: 'assert saubere_eingabe("  hallo welt  ") == "hallo_welt"\nassert saubere_eingabe("a b c") == "a_b_c"' },
          hints: [".strip() zuerst, dann .replace().", 'text.strip().replace(" ", "_")', 'def saubere_eingabe(text):\n    return text.strip().replace(" ", "_")'],
          loesung: 'def saubere_eingabe(text):\n    return text.strip().replace(" ", "_")',
          ex: "Methodenketten (.strip().replace()) verarbeiten einen String in einem durchgehenden Ausdruck.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Dictionaries aus t2l1. Schreibe eine Funktion 'parse_person(zeile)', die eine Zeile im Format 'name,alter,stadt' entgegennimmt und ein dict mit den Schlüsseln 'name', 'alter' (als int) und 'stadt' zurückgibt.",
          starter: "",
          check: { tests: 'ergebnis = parse_person("Anna,23,Berlin")\nassert ergebnis == {"name": "Anna", "alter": 23, "stadt": "Berlin"}' },
          hints: [
            '.split(",") liefert die drei Teile als Liste.',
            "Wandel den zweiten Teil mit int() in eine Zahl um.",
            'def parse_person(zeile):\n    teile = zeile.split(",")\n    return {"name": teile[0], "alter": int(teile[1]), "stadt": teile[2]}',
          ],
          loesung: 'def parse_person(zeile):\n    teile = zeile.split(",")\n    return {"name": teile[0], "alter": int(teile[1]), "stadt": teile[2]}',
          ex: "split() zerlegt Rohtext, int() macht daraus echte Zahlen, das dict gibt allem einen Namen — der Kern von Datenparsing.",
        },
      ],
      lernlog: [
        "[start:stop:step] schneidet Teile aus Strings und Listen",
        "[::-1] kehrt eine Sequenz um",
        ".split() zerlegt einen String in eine Liste",
        ".join() fügt eine Liste zu einem String zusammen",
        ".strip() entfernt Leerzeichen an den Rändern",
        ".replace() ersetzt Teilstrings",
      ],
    },
    {
      id: "t2l5",
      titel: "List Comprehensions",
      icon: "⚡",
      farbe: "var(--orange)",
      kurz: "Listen bauen und filtern in einer Zeile.",
      slides: [
        {
          h: "Transformieren in einer Zeile",
          p: "Eine List Comprehension baut aus einer bestehenden Liste eine neue, indem sie jedes Element durch einen Ausdruck schickt. Sie ersetzt eine for-Schleife mit .append(), die nur eine neue Liste aufbaut.",
          code: "zahlen = [1, 2, 3, 4]\nquadrate = [z ** 2 for z in zahlen]\nprint(quadrate)",
        },
        {
          h: "Filtern mit if",
          p: "Ein <code>if</code> am Ende der Comprehension lässt nur Elemente durch, die die Bedingung erfüllen — Transformieren und Filtern in einem Ausdruck.",
          code: "zahlen = [1, 2, 3, 4, 5, 6]\ngerade = [z for z in zahlen if z % 2 == 0]\nprint(gerade)",
        },
        {
          h: "Wann (nicht) nutzen",
          p: "Comprehensions sind ideal für kurze, klare Transformationen. Wird die Logik komplex — mehrere Bedingungen, mehrere Schritte — ist eine normale Schleife oft lesbarer. Klarheit schlägt Kürze.",
          code: "# klar:\nquadrate = [z ** 2 for z in zahlen]\n# bei mehrstufiger Logik lieber eine normale Schleife",
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Was macht [z * 2 for z in [1, 2, 3]]?",
          code: "",
          opts: ["[1, 2, 3, 1, 2, 3]", "[2, 4, 6]", "[2, 3, 4]", "Fehler"],
          a: 1,
          ex: "Jedes Element wird durch den Ausdruck z * 2 geschickt — Ergebnis ist eine neue Liste.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: "zahlen = [1, 2, 3, 4]\nprint([z for z in zahlen if z > 2])",
          accept: ["[3, 4]"],
          ex: "Das if am Ende filtert — nur Elemente, die die Bedingung erfüllen, landen im Ergebnis.",
        },
        {
          t: "fill",
          q: "Vervollständige die Comprehension, die alle Quadratzahlen von zahlen berechnet.",
          code: "quadrate = [z ___ 2 for z in zahlen]",
          accept: ["**"],
          ex: "** ist der Potenz-Operator — z**2 ist z zum Quadrat.",
        },
        {
          t: "mc",
          q: "Wann ist eine normale for-Schleife einer Comprehension vorzuziehen?",
          code: "",
          opts: ["Immer, Comprehensions sind nur Show", "Wenn die Logik mehrstufig oder unübersichtlich wird", "Nie, Comprehensions sind immer besser lesbar", "Nur bei leeren Listen"],
          a: 1,
          ex: "Comprehensions glänzen bei kurzen, klaren Transformationen — bei komplexer Logik leidet die Lesbarkeit.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: 'woerter = ["Anna", "Bo", "Cem"]\nprint([w for w in woerter if len(w) > 2])',
          accept: ["['Anna', 'Cem']"],
          ex: "len(w) > 2 filtert kurze Wörter heraus — Anna und Cem bleiben übrig, Bo nicht.",
        },
        {
          t: "build",
          q: "Erstelle mit einer List Comprehension eine Liste 'verdoppelt', die jedes Element von 'zahlen' verdoppelt, und gib sie aus.",
          starter: "zahlen = [1, 2, 3]\n",
          check: { stdout: ["[2, 4, 6]"] },
          hints: ["[ausdruck for element in liste]", "verdoppelt = [z * 2 for z in zahlen]", "verdoppelt = [z * 2 for z in zahlen]\nprint(verdoppelt)"],
          loesung: "zahlen = [1, 2, 3]\nverdoppelt = [z * 2 for z in zahlen]\nprint(verdoppelt)",
          ex: "Eine Comprehension baut die neue Liste direkt beim Durchlaufen auf — kein .append() nötig.",
        },
        {
          t: "build",
          q: "Gegeben eine Liste 'zahlen'. Erstelle mit einer Comprehension eine Liste nur der geraden Zahlen und gib sie aus.",
          starter: "zahlen = [1, 2, 3, 4, 5, 6, 7, 8]\n",
          check: { stdout: ["[2, 4, 6, 8]"] },
          hints: ["Filtere mit if am Ende der Comprehension.", "[z for z in zahlen if z % 2 == 0]", "gerade = [z for z in zahlen if z % 2 == 0]\nprint(gerade)"],
          loesung: "zahlen = [1, 2, 3, 4, 5, 6, 7, 8]\ngerade = [z for z in zahlen if z % 2 == 0]\nprint(gerade)",
          ex: "Filtern per if-Klausel ersetzt eine if-Abfrage innerhalb einer klassischen Schleife.",
        },
        {
          t: "build",
          q: "Gegeben eine Liste von Wörtern. Erstelle mit einer Comprehension eine Liste aller Wörter in Großbuchstaben, die länger als 3 Zeichen sind.",
          starter: 'woerter = ["hi", "python", "code", "ok", "programm"]\n',
          check: { stdout: ["['PYTHON', 'CODE', 'PROGRAMM']"] },
          hints: [
            "Kombiniere Transformation (.upper()) und Filter (if len(...) > 3) in einer Comprehension.",
            "[w.upper() for w in woerter if len(w) > 3]",
            "ergebnis = [w.upper() for w in woerter if len(w) > 3]\nprint(ergebnis)",
          ],
          loesung: 'woerter = ["hi", "python", "code", "ok", "programm"]\nergebnis = [w.upper() for w in woerter if len(w) > 3]\nprint(ergebnis)',
          ex: "Transformieren und Filtern in einem Ausdruck ist die Stärke von Comprehensions.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion 'nur_positive(zahlen)', die mit einer List Comprehension nur die positiven Zahlen (> 0) einer Liste zurückgibt.",
          starter: "",
          check: { tests: "assert nur_positive([-2, 5, 0, 3, -1]) == [5, 3]\nassert nur_positive([]) == []" },
          hints: ["Nutze if z > 0 als Filterbedingung.", "return [z for z in zahlen if z > 0]", "def nur_positive(zahlen):\n    return [z for z in zahlen if z > 0]"],
          loesung: "def nur_positive(zahlen):\n    return [z for z in zahlen if z > 0]",
          ex: "Comprehensions als Funktionskörper sind kompakt und trotzdem klar lesbar.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Listen von Dictionaries aus t2l2. Gegeben eine Liste von Produkt-dicts (Schlüssel 'name', 'preis'). Erstelle mit einer Comprehension eine Liste aller Namen der Produkte, die weniger als 5 Euro kosten.",
          starter: 'produkte = [{"name": "Apfel", "preis": 1}, {"name": "Kaese", "preis": 6}, {"name": "Brot", "preis": 2}]\n',
          check: { stdout: ["['Apfel', 'Brot']"] },
          hints: [
            "Der Ausdruck greift auf p['name'] zu, die Bedingung prüft p['preis'].",
            'guenstig = [p["name"] for p in produkte if p["preis"] < 5]',
            'guenstig = [p["name"] for p in produkte if p["preis"] < 5]\nprint(guenstig)',
          ],
          loesung: 'produkte = [{"name": "Apfel", "preis": 1}, {"name": "Kaese", "preis": 6}, {"name": "Brot", "preis": 2}]\nguenstig = [p["name"] for p in produkte if p["preis"] < 5]\nprint(guenstig)',
          ex: "Comprehensions über Listen von dicts sind Alltag: filtern und projizieren in einer Zeile.",
        },
      ],
      lernlog: [
        "List Comprehensions bauen eine neue Liste aus einer bestehenden",
        "[ausdruck for element in liste] transformiert jedes Element",
        "[... for ... if ...] filtert zusätzlich",
        "Comprehensions ersetzen einfache for+append-Schleifen",
        "Bei komplexer Logik ist eine normale Schleife oft lesbarer",
        "Comprehensions funktionieren auch über Listen von Dictionaries",
      ],
    },
    {
      id: "t2l6",
      titel: "Fehlerbehandlung",
      icon: "🚨",
      farbe: "var(--red)",
      kurz: "Programme, die nicht abstürzen.",
      slides: [
        {
          h: "try/except — Fehler gezielt abfangen",
          p: "Code in einem <code>try</code>-Block wird ausprobiert; tritt ein Fehler auf, springt Python in den passenden <code>except</code>-Block, statt das Programm abstürzen zu lassen. Gib immer den konkreten Fehlertyp an, statt alles pauschal abzufangen.",
          code: 'try:\n    zahl = int("abc")\nexcept ValueError:\n    print("Keine gueltige Zahl")',
        },
        {
          h: "Mehrere Fehlertypen",
          p: "Ein Programm kann mehrere except-Blöcke für verschiedene Fehlerarten haben — etwa <code>KeyError</code> bei fehlenden dict-Schlüsseln oder <code>ZeroDivisionError</code> bei Division durch 0. So reagierst du passend statt generisch.",
          code: 'try:\n    ergebnis = 10 / 0\nexcept ZeroDivisionError:\n    print("Nicht durch 0 teilen")',
        },
        {
          h: "else und finally",
          p: "Der <code>else</code>-Block läuft nur, wenn KEIN Fehler auftrat. <code>finally</code> läuft immer — egal ob Fehler oder nicht — nützlich für Aufräumarbeiten.",
          code: 'try:\n    zahl = int("42")\nexcept ValueError:\n    print("Fehler")\nelse:\n    print("Erfolgreich:", zahl)\nfinally:\n    print("Fertig")',
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Welchen Fehlertyp fängst du bei int('abc') ab?",
          code: "",
          opts: ["TypeError", "ValueError", "KeyError", "NameError"],
          a: 1,
          ex: "int() wirft einen ValueError, wenn der String keine gültige Zahl darstellt.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: 'try:\n    print(10 / 0)\nexcept ZeroDivisionError:\n    print("geht nicht")',
          accept: ["geht nicht"],
          ex: "Division durch 0 löst ZeroDivisionError aus, der except-Block fängt sie ab.",
        },
        {
          t: "fill",
          q: "Vervollständige, um einen KeyError abzufangen.",
          code: 'try:\n    print(d["x"])\nexcept ___:\n    print("fehlt")',
          accept: ["KeyError"],
          ex: "Der Zugriff auf einen fehlenden dict-Schlüssel wirft KeyError.",
        },
        {
          t: "mc",
          q: "Wann läuft der else-Block bei try/except?",
          code: "",
          opts: ["Immer", "Nur wenn ein Fehler auftrat", "Nur wenn KEIN Fehler auftrat", "Nie, else ist bei try/except nicht erlaubt"],
          a: 2,
          ex: "else läuft nur bei erfolgreichem try-Block — ideal, um Code zu trennen, der nur bei Erfolg laufen soll.",
        },
        {
          t: "out",
          q: "Was ist die LETZTE Zeile der Ausgabe?",
          code: 'try:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    print("Fehler abgefangen")\nfinally:\n    print("Aufraeumen")',
          accept: ["Aufraeumen"],
          ex: "finally läuft garantiert als letztes im try/except-Block, egal ob ein Fehler auftrat.",
        },
        {
          t: "build",
          q: "Fange einen ValueError ab: versuche int('nope') in eine Zahl umzuwandeln, gib bei Fehler 'Ungueltige Zahl' aus.",
          starter: "",
          check: { stdout: ["Ungueltige Zahl"] },
          hints: ["try/except ValueError.", 'try:\n    int("nope")\nexcept ValueError:\n    print(...)', 'try:\n    int("nope")\nexcept ValueError:\n    print("Ungueltige Zahl")'],
          loesung: 'try:\n    int("nope")\nexcept ValueError:\n    print("Ungueltige Zahl")',
          ex: "try/except fängt den Fehler ab, statt das Programm abstürzen zu lassen.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion 'sichere_division(a, b)', die a/b zurückgibt, aber bei Division durch 0 den String 'Fehler: Division durch 0' zurückgibt statt abzustürzen.",
          starter: "",
          check: { tests: 'assert sichere_division(10, 2) == 5.0\nassert sichere_division(5, 0) == "Fehler: Division durch 0"' },
          hints: [
            "try/except ZeroDivisionError.",
            "return a / b im try, den Fehlertext im except.",
            'def sichere_division(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return "Fehler: Division durch 0"',
          ],
          loesung: 'def sichere_division(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return "Fehler: Division durch 0"',
          ex: "Eine Funktion, die Fehler intern behandelt, ist robuster als eine, die dem Aufrufer den Crash überlässt.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion 'sicherer_zugriff(d, schluessel)', die den Wert zu 'schluessel' aus dict 'd' zurückgibt, oder bei KeyError den String 'nicht gefunden'.",
          starter: "",
          check: { tests: 'assert sicherer_zugriff({"a": 1}, "a") == 1\nassert sicherer_zugriff({"a": 1}, "b") == "nicht gefunden"' },
          hints: [
            "try/except KeyError um den Zugriff d[schluessel].",
            "return d[schluessel] im try.",
            'def sicherer_zugriff(d, schluessel):\n    try:\n        return d[schluessel]\n    except KeyError:\n        return "nicht gefunden"',
          ],
          loesung: 'def sicherer_zugriff(d, schluessel):\n    try:\n        return d[schluessel]\n    except KeyError:\n        return "nicht gefunden"',
          ex: "Auch wenn .get() hier eleganter wäre — try/except zeigt, dass jeder Fehlertyp gezielt behandelbar ist.",
        },
        {
          t: "build",
          q: "Frage den Nutzer mit input() nach einer Zahl. Wandle sie mit int() um. Wenn keine gültige Zahl eingegeben wurde, gib 'Ungueltige Eingabe' aus, sonst gib die verdoppelte Zahl aus.",
          starter: "",
          check: { stdout: ["Ungueltige Eingabe"], stdin: ["abc"] },
          hints: [
            "Nutze try/except ValueError um int(input()).",
            'try:\n    zahl = int(input())\n    print(zahl * 2)\nexcept ValueError:\n    print("Ungueltige Eingabe")',
            'try:\n    zahl = int(input())\n    print(zahl * 2)\nexcept ValueError:\n    print("Ungueltige Eingabe")',
          ],
          loesung: 'try:\n    zahl = int(input())\n    print(zahl * 2)\nexcept ValueError:\n    print("Ungueltige Eingabe")',
          ex: "Nutzereingaben sind nie garantiert gültig — try/except macht dein Programm robust gegen Tippfehler.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: .get() aus t2l1. Schreibe eine Funktion 'punkte_holen(ergebnisse, name)', die den Punktestand zu 'name' aus dict 'ergebnisse' zurückgibt. Ist der Name nicht enthalten ODER der Wert keine Zahl (zum Beispiel ein String), gib 0 zurück. Nutze try/except für die Typprüfung.",
          starter: "",
          check: {
            tests: 'assert punkte_holen({"anna": 10, "ben": "?"}, "anna") == 10\nassert punkte_holen({"anna": 10, "ben": "?"}, "ben") == 0\nassert punkte_holen({"anna": 10}, "cem") == 0',
          },
          hints: [
            "Hole den Wert zuerst robust mit ergebnisse.get(name, 0).",
            "Prüfe mit try/except TypeError, ob mit dem Wert gerechnet werden kann.",
            "def punkte_holen(ergebnisse, name):\n    wert = ergebnisse.get(name, 0)\n    try:\n        return wert + 0\n    except TypeError:\n        return 0",
          ],
          loesung: "def punkte_holen(ergebnisse, name):\n    wert = ergebnisse.get(name, 0)\n    try:\n        return wert + 0\n    except TypeError:\n        return 0",
          ex: "Zwei Robustheits-Werkzeuge kombiniert: .get() gegen fehlende Schlüssel, try/except gegen falsche Typen.",
        },
      ],
      lernlog: [
        "try/except fängt Fehler ab, statt das Programm abstürzen zu lassen",
        "Gezielte except-Blöcke (ValueError, KeyError, ZeroDivisionError) statt pauschales Abfangen",
        "else läuft nur bei Erfolg, finally läuft immer",
        "int() wirft ValueError bei ungültigen Zahl-Strings",
        "Fehlende dict-Schlüssel werfen KeyError",
        "Robuste Eingabeverarbeitung kombiniert try/except mit input()",
      ],
    },
    {
      id: "t2l7",
      titel: "Dateien",
      icon: "📄",
      farbe: "var(--teal)",
      kurz: "Daten überleben das Programmende.",
      slides: [
        {
          h: "Dateien öffnen mit with",
          p: '<code>with open(datei, modus) as f:</code> öffnet eine Datei und schließt sie garantiert wieder — auch bei einem Fehler. Modus "w" schreibt (überschreibt), "r" liest, "a" hängt an.',
          code: 'with open("notiz.txt", "w") as f:\n    f.write("Hallo Datei\\n")',
        },
        {
          h: "Zeilen lesen",
          p: "Mit <code>f.read()</code> liest du den ganzen Inhalt als einen String, mit einer for-Schleife über <code>f</code> liest du Zeile für Zeile. <code>.strip()</code> entfernt dabei die Zeilenumbrüche.",
          code: 'with open("notiz.txt", "r") as f:\n    for zeile in f:\n        print(zeile.strip())',
        },
        {
          h: "Anhängen mit a",
          p: 'Modus "a" (append) hängt neuen Text ans Ende einer Datei an, statt sie zu überschreiben — praktisch für Logs, die wachsen.',
          code: 'with open("notiz.txt", "a") as f:\n    f.write("Noch eine Zeile\\n")',
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Welcher Modus überschreibt eine Datei komplett?",
          code: "",
          opts: ["'r'", "'w'", "'a'", "'x'"],
          a: 1,
          ex: "'w' (write) überschreibt den kompletten Inhalt, falls die Datei schon existiert.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: 'with open("t.txt", "w") as f:\n    f.write("Hi")\nwith open("t.txt", "r") as f:\n    print(f.read())',
          accept: ["Hi"],
          ex: "f.read() liefert den kompletten Dateiinhalt als einen String zurück.",
        },
        {
          t: "fill",
          q: "Vervollständige, um eine Datei zum Lesen zu öffnen.",
          code: 'with open("t.txt", ___) as f:\n    print(f.read())',
          accept: ["r", "'r'", '"r"'],
          ex: "'r' ist der Modus zum Lesen — auch der Standardwert, wenn kein Modus angegeben wird.",
        },
        {
          t: "mc",
          q: "Warum ist 'with open(...) as f' besser als 'f = open(...)' ohne with?",
          code: "",
          opts: ["with ist schneller", "with schliesst die Datei garantiert, auch bei Fehlern", "with erlaubt mehr Dateimodi", "Kein Unterschied"],
          a: 1,
          ex: "with garantiert das Schliessen der Datei über einen Context Manager, selbst wenn im Block ein Fehler auftritt.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: 'with open("log.txt", "w") as f:\n    f.write("Zeile1\\n")\nwith open("log.txt", "a") as f:\n    f.write("Zeile2\\n")\nwith open("log.txt", "r") as f:\n    inhalt = f.read()\nprint(len(inhalt.splitlines()))',
          accept: ["2"],
          ex: "'a' hängt an, statt zu überschreiben — die Datei enthält am Ende zwei Zeilen.",
        },
        {
          t: "build",
          q: "Schreibe den Text 'Hallo Datei' in eine neue Datei 'test.txt', öffne sie danach zum Lesen und gib den Inhalt aus.",
          starter: "",
          check: { stdout: ["Hallo Datei"] },
          hints: [
            "Modus 'w' zum Schreiben, 'r' zum Lesen.",
            'with open("test.txt", "w") as f:\n    f.write("Hallo Datei")',
            'with open("test.txt", "w") as f:\n    f.write("Hallo Datei")\nwith open("test.txt", "r") as f:\n    print(f.read())',
          ],
          loesung: 'with open("test.txt", "w") as f:\n    f.write("Hallo Datei")\nwith open("test.txt", "r") as f:\n    print(f.read())',
          ex: "Schreiben und Lesen im selben Programm — die Datei ist ein einfacher, persistenter Zwischenspeicher.",
        },
        {
          t: "build",
          q: "Schreibe drei Zeilen ('eins', 'zwei', 'drei') in die Datei 'liste.txt' (je eine pro Zeile), lies sie dann zeilenweise ein und gib jede Zeile ohne Zeilenumbruch aus.",
          starter: "",
          check: { stdout: ["eins", "zwei", "drei"] },
          hints: [
            "f.write() braucht \\n am Ende jeder Zeile, wenn du mehrere schreibst.",
            "Beim Lesen: for zeile in f: und zeile.strip()",
            'with open("liste.txt", "w") as f:\n    f.write("eins\\nzwei\\ndrei\\n")\nwith open("liste.txt", "r") as f:\n    for zeile in f:\n        print(zeile.strip())',
          ],
          loesung: 'with open("liste.txt", "w") as f:\n    f.write("eins\\nzwei\\ndrei\\n")\nwith open("liste.txt", "r") as f:\n    for zeile in f:\n        print(zeile.strip())',
          ex: "Zeilenweises Lesen mit .strip() ist der Standardweg, Textdateien robust zu verarbeiten.",
        },
        {
          t: "build",
          q: "Schreibe 'Start' in die Datei 'log.txt' (überschreiben), hänge danach 'Ende' an (append), lies die Datei komplett und gib die Anzahl der Zeilen aus.",
          starter: "",
          check: { stdout: ["2"] },
          hints: [
            "Erst 'w' zum Schreiben, dann 'a' zum Anhängen — je mit \\n am Zeilenende.",
            "Beim Lesen: f.read().splitlines() gibt eine Liste der Zeilen zurück.",
            'with open("log.txt", "w") as f:\n    f.write("Start\\n")\nwith open("log.txt", "a") as f:\n    f.write("Ende\\n")\nwith open("log.txt", "r") as f:\n    zeilen = f.read().splitlines()\nprint(len(zeilen))',
          ],
          loesung: 'with open("log.txt", "w") as f:\n    f.write("Start\\n")\nwith open("log.txt", "a") as f:\n    f.write("Ende\\n")\nwith open("log.txt", "r") as f:\n    zeilen = f.read().splitlines()\nprint(len(zeilen))',
          ex: "'a' ist der Modus für wachsende Dateien wie Logs — nichts geht verloren.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion 'zeilen_zaehlen(pfad)', die eine Datei öffnet und die Anzahl ihrer Zeilen zurückgibt. Lege vorher selbst eine Testdatei mit mehreren Zeilen an, um die Funktion zu prüfen.",
          starter: "",
          check: { tests: 'assert zeilen_zaehlen("daten.txt") == 3' },
          hints: [
            "Lege zuerst mit open(..., 'w') eine Testdatei mit mehreren Zeilen an.",
            "f.readlines() gibt eine Liste aller Zeilen zurück — len() davon ist die Anzahl.",
            'def zeilen_zaehlen(pfad):\n    with open(pfad, "r") as f:\n        return len(f.readlines())',
          ],
          loesung: 'with open("daten.txt", "w") as f:\n    f.write("a\\nb\\nc\\n")\n\ndef zeilen_zaehlen(pfad):\n    with open(pfad, "r") as f:\n        return len(f.readlines())',
          ex: "Eine Funktion, die einen Dateipfad entgegennimmt, ist wiederverwendbar für jede Datei — nicht nur eine fest verdrahtete.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: .split() aus t2l4. Schreibe die Zeilen 'Anna,23' und 'Ben,31' in die Datei 'personen.txt'. Lies sie danach ein, zerlege jede Zeile am Komma und gib pro Zeile 'name ist alter Jahre alt' aus.",
          starter: "",
          check: { stdout: ["Anna ist 23 Jahre alt", "Ben ist 31 Jahre alt"] },
          hints: [
            "Schreibe zuerst beide Zeilen mit \\n getrennt in die Datei.",
            'Beim Lesen: zeile.strip().split(",") gibt dir [name, alter].',
            'with open("personen.txt", "w") as f:\n    f.write("Anna,23\\nBen,31\\n")\nwith open("personen.txt", "r") as f:\n    for zeile in f:\n        name, alter = zeile.strip().split(",")\n        print(name, "ist", alter, "Jahre alt")',
          ],
          loesung: 'with open("personen.txt", "w") as f:\n    f.write("Anna,23\\nBen,31\\n")\nwith open("personen.txt", "r") as f:\n    for zeile in f:\n        name, alter = zeile.strip().split(",")\n        print(name, "ist", alter, "Jahre alt")',
          ex: "Dateien speichern rohen Text — .split() und .strip() verwandeln ihn wieder in strukturierte Daten.",
        },
      ],
      lernlog: [
        "with open(...) as f schliesst Dateien garantiert",
        "'w' überschreibt, 'r' liest, 'a' hängt an",
        "for zeile in f liest eine Datei zeilenweise",
        ".strip() entfernt den Zeilenumbruch beim Lesen",
        "f.read() liefert den gesamten Inhalt als String",
        "Geschriebener Text braucht \\n, um mehrzeilig zu sein",
      ],
    },
    {
      id: "t2l8",
      titel: "Module & Standardbibliothek",
      icon: "📚",
      farbe: "var(--gold)",
      kurz: "Fertige Werkzeuge statt Neuerfindung.",
      slides: [
        {
          h: "import — fremden Code nutzen",
          p: "Mit <code>import</code> lädst du ein Modul aus Pythons Standardbibliothek — fertige, getestete Werkzeuge statt Neuerfindung. Zugriff auf Funktionen erfolgt über <code>modul.funktion()</code>.",
          code: "import math\nprint(math.sqrt(16))",
        },
        {
          h: "random — Zufall kontrolliert nutzen",
          p: "<code>random.randint(a, b)</code> liefert eine zufällige ganze Zahl zwischen a und b (inklusive). Mit <code>random.seed(...)</code> machst du Zufallsergebnisse reproduzierbar — wichtig zum Testen.",
          code: "import random\nrandom.seed(1)\nprint(random.randint(1, 6))",
        },
        {
          h: "datetime — mit Datum und Zeit arbeiten",
          p: "<code>datetime.date</code> repräsentiert ein Kalenderdatum. Damit lassen sich Daten erzeugen, vergleichen und die Zeit dazwischen berechnen, ohne die Kalenderlogik selbst zu schreiben.",
          code: "from datetime import date\nheute = date(2024, 1, 15)\nprint(heute.year)",
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Wie rufst du sqrt aus dem math-Modul auf?",
          code: "",
          opts: ["sqrt(16)", "math.sqrt(16)", "import.sqrt(16)", "math->sqrt(16)"],
          a: 1,
          ex: "Nach import math greifst du über math.funktion() auf die Werkzeuge des Moduls zu.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: "import math\nprint(math.floor(3.9))",
          accept: ["3"],
          ex: "math.floor() rundet immer ab zur nächstkleineren ganzen Zahl.",
        },
        {
          t: "fill",
          q: "Vervollständige den Import, um das gesamte math-Modul zu laden.",
          code: "___ math",
          accept: ["import"],
          ex: "import lädt ein Modul, danach ist es über seinen Namen ansprechbar.",
        },
        {
          t: "mc",
          q: "Was macht random.seed(1)?",
          code: "",
          opts: ["Erzeugt eine Zufallszahl 1", "Macht nachfolgende Zufallszahlen reproduzierbar", "Deaktiviert den Zufallsgenerator", "Setzt eine Obergrenze für Zufallszahlen"],
          a: 1,
          ex: "Ein fester seed sorgt dafür, dass die 'zufällige' Sequenz bei jedem Lauf identisch ist — wichtig zum Testen.",
        },
        {
          t: "out",
          q: "Was gibt das aus?",
          code: "from datetime import date\nd = date(2024, 3, 1)\nprint(d.month)",
          accept: ["3"],
          ex: "date-Objekte speichern Jahr, Monat und Tag als eigene Attribute.",
        },
        {
          t: "build",
          q: "Importiere das math-Modul und gib math.sqrt(81) aus.",
          starter: "",
          check: { stdout: ["9.0"] },
          hints: ["import math am Anfang.", "math.sqrt() gibt die Quadratwurzel zurück.", "import math\nprint(math.sqrt(81))"],
          loesung: "import math\nprint(math.sqrt(81))",
          ex: "math.sqrt() gibt immer einen float zurück, auch bei einer perfekten Quadratzahl.",
        },
        {
          t: "build",
          q: "Ziehe mit random.randint(1, 6) eine simulierte Würfelzahl und speichere sie in der Variable 'wurf'.",
          starter: "",
          check: { tests: "assert 1 <= wurf <= 6" },
          hints: ["import random nicht vergessen.", "random.randint(1, 6) liefert eine Ganzzahl inklusive beider Grenzen.", "import random\nwurf = random.randint(1, 6)"],
          loesung: "import random\nwurf = random.randint(1, 6)",
          ex: "random.randint(a, b) schliesst beide Grenzen ein — bei einem Würfel also 1 bis 6.",
        },
        {
          t: "build",
          q: "Erstelle mit einer Schleife eine Liste 'wuerfe' mit 5 simulierten Würfelwürfen (random.randint(1, 6)).",
          starter: "",
          check: { tests: "assert len(wuerfe) == 5\nassert all(1 <= w <= 6 for w in wuerfe)" },
          hints: [
            "import random und eine leere Liste zum Sammeln.",
            "Nutze eine for-Schleife mit range(5) und .append().",
            "import random\nwuerfe = []\nfor _ in range(5):\n    wuerfe.append(random.randint(1, 6))",
          ],
          loesung: "import random\nwuerfe = []\nfor _ in range(5):\n    wuerfe.append(random.randint(1, 6))",
          ex: "Bei echtem Zufall prüfst du Eigenschaften (Länge, Wertebereich) statt exakter Werte — die Zahlen selbst sind bei jedem Lauf anders.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion 'tage_bis_ende_jahres(jahr, monat, tag)', die mit dem datetime-Modul berechnet, wie viele Tage von diesem Datum bis zum 31. Dezember desselben Jahres vergehen (als int, über .days).",
          starter: "",
          check: { tests: "assert tage_bis_ende_jahres(2024, 12, 31) == 0\nassert tage_bis_ende_jahres(2024, 12, 1) == 30\nassert tage_bis_ende_jahres(2024, 1, 1) == 365" },
          hints: [
            "from datetime import date importiert die date-Klasse.",
            "Die Differenz zweier date-Objekte hat ein .days-Attribut.",
            "def tage_bis_ende_jahres(jahr, monat, tag):\n    start = date(jahr, monat, tag)\n    ende = date(jahr, 12, 31)\n    return (ende - start).days",
          ],
          loesung: "from datetime import date\n\ndef tage_bis_ende_jahres(jahr, monat, tag):\n    start = date(jahr, monat, tag)\n    ende = date(jahr, 12, 31)\n    return (ende - start).days",
          ex: "Datumsarithmetik von Hand (Schaltjahre, Monatslängen) ist fehleranfällig — datetime übernimmt das zuverlässig.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Fehlerbehandlung aus t2l6. Schreibe eine Funktion 'sichere_wurzel(zahl)', die math.sqrt(zahl) zurückgibt, bei negativen Zahlen (ValueError) aber None zurückgibt statt abzustürzen.",
          starter: "",
          check: { tests: "assert sichere_wurzel(16) == 4.0\nassert sichere_wurzel(-4) is None" },
          hints: [
            "math.sqrt() wirft bei negativen Zahlen einen ValueError.",
            "Fange ihn mit try/except ab wie in t2l6.",
            "def sichere_wurzel(zahl):\n    import math\n    try:\n        return math.sqrt(zahl)\n    except ValueError:\n        return None",
          ],
          loesung: "import math\n\ndef sichere_wurzel(zahl):\n    try:\n        return math.sqrt(zahl)\n    except ValueError:\n        return None",
          ex: "Standardbibliothek-Funktionen können genauso Fehler werfen wie eigener Code — try/except schützt in beiden Fällen.",
        },
      ],
      lernlog: [
        "import lädt ein Modul der Standardbibliothek",
        "math stellt mathematische Funktionen wie sqrt() und floor() bereit",
        "random.randint(a, b) liefert eine Zufallszahl inklusive beider Grenzen",
        "random.seed() macht Zufallsergebnisse reproduzierbar",
        "datetime.date bildet Kalenderdaten ab und erlaubt Datumsarithmetik",
        "Bei Zufall prüft man Eigenschaften (Bereich, Länge) statt exakter Werte",
      ],
    },
  ],
  werkstatt: [
    {
      id: "t2p1",
      titel: "Vokabel-Trainer",
      farbe: "var(--blue)",
      schwierigkeit: 2,
      brief:
        "Baue einen Vokabel-Trainer, der Vokabeln aus einem Dictionary abfragt. Hinterlege mindestens vier Englisch-Deutsch-Paare in einem dict. Frage für jede Vokabel per input() nach der Übersetzung. Vergleiche die Eingabe robust gegen Groß-/Kleinschreibung und überflüssige Leerzeichen. Zähle die richtigen Antworten mit. Gib am Ende den Punktestand im Format 'Punktestand: x/y' aus.",
      transfer: ["t2l1", "t2l6", "teil1"],
      starter: "",
      check: {
        stdout: ["Punktestand: 3/4"],
        stdin: ["katze", "hund", "falsch", "baum"],
      },
      hints: [
        "Speichere die Vokabeln in einem dict mit Englisch als Schlüssel und Deutsch als Wert.",
        "Vergleiche die Antwort robust: .strip().lower() gegen die hinterlegte Übersetzung.",
        'vokabeln = {"cat": "katze", "dog": "hund", "house": "haus", "tree": "baum"}\npunkte = 0\nfor wort, uebersetzung in vokabeln.items():\n    antwort = input().strip().lower()\n    if antwort == uebersetzung:\n        punkte += 1\nprint(f"Punktestand: {punkte}/{len(vokabeln)}")',
      ],
      loesung:
        'vokabeln = {"cat": "katze", "dog": "hund", "house": "haus", "tree": "baum"}\npunkte = 0\nfor wort, uebersetzung in vokabeln.items():\n    antwort = input().strip().lower()\n    if antwort == uebersetzung:\n        punkte += 1\nprint(f"Punktestand: {punkte}/{len(vokabeln)}")',
    },
    {
      id: "t2p2",
      titel: "Kassensystem",
      farbe: "var(--lime)",
      schwierigkeit: 2,
      brief:
        "Baue ein einfaches Kassensystem für einen kleinen Laden. Hinterlege Produkte als dict mit Namen als Schlüssel und Preis als Wert. Sammle mehrere gekaufte Produkte in einem Warenkorb (Liste), darunter auch ein ungültiges Produkt. Gib pro Position eine Bon-Zeile im Format 'produkt: preis' aus. Fange ungültige Produktnamen mit try/except ab und gib stattdessen 'produkt: nicht gefunden' aus, ohne abzustürzen. Gib am Ende die Zeile 'Gesamt: summe' mit der Summe aller gültigen Positionen aus.",
      transfer: ["t2l1", "t2l4", "t2l6"],
      starter: "",
      check: {
        stdout: ["apfel: 2", "milch: 1", "unbekannt: nicht gefunden", "brot: 3", "Gesamt: 6"],
      },
      hints: [
        "Nutze ein dict für Produkt -> Preis.",
        "Fange den Zugriff auf unbekannte Produkte mit try/except KeyError ab.",
        'for artikel in warenkorb:\n    try:\n        preis = produkte[artikel]\n        gesamt += preis\n        print(f"{artikel}: {preis}")\n    except KeyError:\n        print(f"{artikel}: nicht gefunden")',
      ],
      loesung:
        'produkte = {"apfel": 2, "brot": 3, "milch": 1}\nwarenkorb = ["apfel", "milch", "unbekannt", "brot"]\ngesamt = 0\nfor artikel in warenkorb:\n    try:\n        preis = produkte[artikel]\n        gesamt += preis\n        print(f"{artikel}: {preis}")\n    except KeyError:\n        print(f"{artikel}: nicht gefunden")\nprint(f"Gesamt: {gesamt}")',
    },
    {
      id: "t2p3",
      titel: "Log-Analysator",
      farbe: "var(--teal)",
      schwierigkeit: 3,
      brief:
        "Baue einen Log-Analysator für eine kleine Log-Datei. Schreibe zuerst ein paar Beispielzeilen im Format 'LEVEL: Nachricht' in eine Datei. Lies die Datei zeilenweise wieder ein und entferne die Zeilenumbrüche. Zerlege jede Zeile am Doppelpunkt und zähle pro Level, wie oft es vorkommt, in einem dict. Gib die Statistik sortiert nach Level-Namen im Format 'LEVEL: anzahl' aus. Ermittle zusätzlich mit einer List Comprehension, wie viele Zeilen mit 'ERROR' beginnen, und gib diese Anzahl als 'Fehleranzahl: anzahl' aus.",
      transfer: ["t2l4", "t2l5", "t2l7"],
      starter: "",
      check: {
        stdout: ["ERROR: 2", "INFO: 2", "WARNING: 1", "Fehleranzahl: 2"],
      },
      hints: [
        "Schreibe die Log-Zeilen zuerst in eine Datei, lies sie danach zeilenweise wieder ein.",
        'zeile.split(":")[0] liefert das Level, stats.get(level, 0) + 1 zählt hoch.',
        'for level in sorted(stats):\n    print(f"{level}: {stats[level]}")\nfehler = [z for z in zeilen if z.startswith("ERROR")]\nprint(f"Fehleranzahl: {len(fehler)}")',
      ],
      loesung:
        'with open("log.txt", "w") as f:\n    f.write("INFO: Start\\nERROR: Verbindung verloren\\nWARNING: Speicher knapp\\nERROR: Timeout\\nINFO: Ende\\n")\n\nwith open("log.txt", "r") as f:\n    zeilen = [z.strip() for z in f]\n\nstats = {}\nfor zeile in zeilen:\n    level = zeile.split(":")[0]\n    stats[level] = stats.get(level, 0) + 1\n\nfor level in sorted(stats):\n    print(f"{level}: {stats[level]}")\n\nfehler = [z for z in zeilen if z.startswith("ERROR")]\nprint(f"Fehleranzahl: {len(fehler)}")',
    },
    {
      id: "t2p4",
      titel: "Würfel-Duell",
      farbe: "var(--gold)",
      schwierigkeit: 3,
      brief:
        "Baue ein Würfel-Duell zwischen zwei Spielern, alles sauber in Funktionen strukturiert. Eine Funktion simuliert einen einzelnen Würfelwurf mit random.randint(1, 6). Eine zweite Funktion spielt eine Runde: beide Spieler würfeln, ein Vergleich bestimmt den Gewinner, das Ergebnis wird als dict zurückgegeben. Eine dritte Funktion spielt mehrere Runden und sammelt die Ergebnisse als Liste von dicts (Runden-Historie). Schreibe zusätzlich eine Auswertungsfunktion, die aus der Historie zählt, wie oft jeder Spieler gewonnen hat, inklusive Unentschieden. Setze der Reproduzierbarkeit halber einen festen random.seed().",
      transfer: ["t2l8", "t2l1", "teil1"],
      starter: "",
      check: {
        tests:
          'verlauf2 = spiele_duell("Anna", "Ben", 5)\nassert len(verlauf2) == 5\nassert all(set(r.keys()) == {"spieler1", "spieler2", "gewinner"} for r in verlauf2)\nassert all(1 <= r["spieler1"] <= 6 and 1 <= r["spieler2"] <= 6 for r in verlauf2)\nassert all(r["gewinner"] in ("Anna", "Ben", "Unentschieden") for r in verlauf2)\nauswertung2 = endauswertung(verlauf2, "Anna", "Ben")\nassert sum(auswertung2.values()) == 5\nassert set(auswertung2.keys()) == {"Anna", "Ben", "Unentschieden"}',
      },
      hints: [
        "Schreibe zuerst eine Funktion, die einen einzelnen Würfelwurf simuliert (random.randint(1, 6)).",
        "Eine Rundenfunktion lässt beide Spieler würfeln und gibt ein dict mit beiden Würfen und dem Gewinner zurück.",
        'def spiele_runde(spieler1, spieler2):\n    wurf1 = wuerfeln()\n    wurf2 = wuerfeln()\n    if wurf1 > wurf2:\n        gewinner = spieler1\n    elif wurf2 > wurf1:\n        gewinner = spieler2\n    else:\n        gewinner = "Unentschieden"\n    return {"spieler1": wurf1, "spieler2": wurf2, "gewinner": gewinner}',
      ],
      loesung:
        'import random\nrandom.seed(3)\n\ndef wuerfeln():\n    return random.randint(1, 6)\n\ndef spiele_runde(spieler1, spieler2):\n    wurf1 = wuerfeln()\n    wurf2 = wuerfeln()\n    if wurf1 > wurf2:\n        gewinner = spieler1\n    elif wurf2 > wurf1:\n        gewinner = spieler2\n    else:\n        gewinner = "Unentschieden"\n    return {"spieler1": wurf1, "spieler2": wurf2, "gewinner": gewinner}\n\ndef spiele_duell(spieler1, spieler2, runden):\n    verlauf = []\n    for _ in range(runden):\n        verlauf.append(spiele_runde(spieler1, spieler2))\n    return verlauf\n\ndef endauswertung(verlauf, spieler1, spieler2):\n    ergebnis = {spieler1: 0, spieler2: 0, "Unentschieden": 0}\n    for runde in verlauf:\n        ergebnis[runde["gewinner"]] += 1\n    return ergebnis\n\nspieler1 = "Anna"\nspieler2 = "Ben"\nverlauf = spiele_duell(spieler1, spieler2, 5)\nauswertung = endauswertung(verlauf, spieler1, spieler2)\nprint(f"{spieler1}: {auswertung[spieler1]} Siege")\nprint(f"{spieler2}: {auswertung[spieler2]} Siege")',
    },
  ],
};
