// TEIL 1 — "Die Basics" — vollständiger Content nach MASTERPROMPT Abschnitt 4, 6, 8.
export default {
  id: "teil1",
  nummer: 1,
  titel: "Die Basics",
  untertitel: "Erste Schritte mit Python",
  farbe: "var(--cyan)",
  voraussetzung: null,
  lektionen: [
    // ───────────────────────────────────────────── L1: print() & Kommentare
    {
      id: "t1l1",
      titel: "print() & Kommentare",
      icon: "🖨",
      farbe: "var(--cyan)",
      kurz: "Deine erste Ausgabe.",
      slides: [
        {
          h: "print() gibt Text aus",
          p: "Mit <code>print()</code> zeigst du Text im Terminal an. Der Text steht in Anführungszeichen — das nennt man einen String. Ohne <code>print()</code> passiert bei der Ausführung eines Skripts nichts Sichtbares.",
          code: 'print("Hallo Welt")',
        },
        {
          h: "Mehrere Werte",
          p: "Du kannst mehrere Werte durch Komma trennen — <code>print()</code> fügt zwischen ihnen automatisch ein Leerzeichen ein. Das funktioniert mit Text und Zahlen gemischt.",
          code: 'print("Alter:", 21)',
        },
        {
          h: "Kommentare",
          p: "Mit <code>#</code> beginnt ein Kommentar. Python ignoriert alles, was danach in der Zeile steht — nützlich für Notizen an dich selbst oder andere. Kommentare erzeugen nie eine Ausgabe.",
          code: '# das wird nicht ausgeführt\nprint("aber das schon")',
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Was gibt dieser Code aus?",
          code: 'print("Hi")',
          opts: ["Hi", '"Hi"', "print(Hi)", "Fehler"],
          a: 0,
          ex: "print() gibt den Inhalt der Anführungszeichen ohne die Zeichen selbst aus.",
        },
        {
          t: "out",
          q: "Was erscheint im Terminal?",
          code: 'print("A", "B")',
          accept: ["A B"],
          ex: "print() trennt mehrere Argumente automatisch mit einem Leerzeichen.",
        },
        {
          t: "fill",
          q: "Vervollständige den Aufruf, der 'Test' ausgibt:",
          code: '___("Test")',
          accept: ["print"],
          ex: "print ist die Funktion für Konsolenausgabe.",
        },
        {
          t: "mc",
          q: "Welche Zeile ist ein Kommentar?",
          code: '# print("x")\nprint("y")',
          opts: ["Zeile 1", "Zeile 2", "beide", "keine"],
          a: 0,
          ex: "Zeilen, die mit # beginnen, werden von Python komplett ignoriert.",
        },
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: '# print("versteckt")\nprint("sichtbar")',
          accept: ["sichtbar"],
          ex: "Die kommentierte Zeile wird nie ausgeführt — sie existiert nur für Menschen, die den Code lesen.",
        },
        {
          t: "build",
          q: "Gib drei Zeilen aus: deinen Namen, dein Studienfach, dein Lernziel.",
          starter: "",
          check: { stdout: ["Simon", "Informatik", "Python lernen"] },
          hints: [
            "Nutze drei print()-Aufrufe untereinander.",
            "Jede print()-Zeile erzeugt automatisch eine neue Ausgabezeile.",
            'print("Simon")\nprint("Informatik")\nprint("Python lernen")',
          ],
          loesung: 'print("Simon")\nprint("Informatik")\nprint("Python lernen")',
          ex: "Mehrere print()-Aufrufe nacheinander erzeugen mehrere Ausgabezeilen, jede endet automatisch mit einem Zeilenumbruch.",
        },
        {
          t: "build",
          q: "Gib 'Hallo PY.QUEST' aus, dann eine Kommentarzeile (die nichts ausgibt), dann 'Fertig!'.",
          starter: "",
          check: { stdout: ["Hallo PY.QUEST", "Fertig!"] },
          hints: [
            "Kommentare beginnen mit #.",
            "Ein Kommentar erzeugt keine eigene Ausgabezeile.",
            'print("Hallo PY.QUEST")\n# hier folgt der Abschluss\nprint("Fertig!")',
          ],
          loesung: 'print("Hallo PY.QUEST")\n# hier folgt der Abschluss\nprint("Fertig!")',
          ex: "Kommentare sind reine Dokumentation für Menschen, nicht für den Interpreter — sie verändern die Ausgabe nie.",
        },
        {
          t: "build",
          q: "Gib mit einem einzigen print()-Aufruf 'Team' und 'Rot' in einer Zeile aus (im Code durch Komma getrennt).",
          starter: "",
          check: { stdout: ["Team Rot"] },
          hints: [
            "print() kann mehrere Argumente auf einmal bekommen.",
            "Trenne die beiden Werte im Aufruf durch ein Komma.",
            'print("Team", "Rot")',
          ],
          loesung: 'print("Team", "Rot")',
          ex: "Kommagetrennte Argumente landen alle in derselben Ausgabezeile, automatisch durch ein Leerzeichen getrennt.",
        },
        {
          t: "build",
          q: "Gib vier Zeilen aus: 'Schritt 1', 'Schritt 2', 'Schritt 3', 'Fertig!' — kommentiere den Code so, dass klar wird, was die letzte Zeile bedeutet.",
          starter: "",
          check: { stdout: ["Schritt 1", "Schritt 2", "Schritt 3", "Fertig!"] },
          hints: [
            "Vier print()-Aufrufe nacheinander, ein Kommentar irgendwo dazwischen.",
            "Der Kommentar ändert nichts an der Ausgabe, er erklärt nur den Code.",
            'print("Schritt 1")\nprint("Schritt 2")\nprint("Schritt 3")\n# Abschlussmeldung\nprint("Fertig!")',
          ],
          loesung: 'print("Schritt 1")\nprint("Schritt 2")\nprint("Schritt 3")\n# Abschlussmeldung\nprint("Fertig!")',
          ex: "Gute Kommentare erklären das Warum eines Codeabschnitts, nicht bloß, was ohnehin lesbar ist.",
        },
        {
          t: "build",
          q: "Schreibe eine Kopfzeile für ein Skript: eine Kommentarzeile, die den Zweck beschreibt, dann per print() 'PY.QUEST', '----------' und 'Teil 1: Die Basics' — je eine eigene Zeile.",
          starter: "",
          check: { stdout: ["PY.QUEST", "----------", "Teil 1: Die Basics"] },
          hints: [
            "Ein Kommentar oben beschreibt das ganze Skript, er erzeugt keine Ausgabe.",
            "Danach drei print()-Aufrufe in der richtigen Reihenfolge.",
            '# Titelanzeige fuer PY.QUEST\nprint("PY.QUEST")\nprint("----------")\nprint("Teil 1: Die Basics")',
          ],
          loesung: '# Titelanzeige fuer PY.QUEST\nprint("PY.QUEST")\nprint("----------")\nprint("Teil 1: Die Basics")',
          ex: "Reihenfolge im Code = Reihenfolge der Ausgabe, streng von oben nach unten — Kommentare zählen dabei nicht mit.",
        },
      ],
      lernlog: [
        "print() gibt Text im Terminal aus",
        "Mehrere Argumente in print() werden automatisch mit Leerzeichen getrennt",
        "Strings stehen in Anführungszeichen",
        "# beginnt einen Kommentar, der vom Interpreter ignoriert wird",
        "Code wird strikt von oben nach unten ausgeführt",
        "Kommentare dokumentieren das Warum, nicht das Was",
      ],
    },

    // ───────────────────────────────────────────── L2: Variablen & Datentypen
    {
      id: "t1l2",
      titel: "Variablen & Datentypen",
      icon: "📦",
      farbe: "var(--magenta)",
      kurz: "Werte einen Namen geben.",
      slides: [
        {
          h: "Was ist eine Variable?",
          p: "Eine Variable ist ein Name für einen Wert. Mit <code>=</code> weist du den Wert zu — das ist keine Gleichheitsprüfung, sondern eine Zuweisung. Danach kannst du den Namen überall nutzen, wo du den Wert brauchst.",
          code: 'alter = 21\nprint(alter)',
        },
        {
          h: "Datentypen",
          p: "Die Grund-Datentypen sind <code>int</code> (Ganzzahl), <code>float</code> (Kommazahl), <code>str</code> (Text) und <code>bool</code> (True/False). Mit <code>type()</code> findest du heraus, welchen Typ ein Wert hat.",
          code: 'preis = 3.99\nprint(type(preis))',
        },
        {
          h: "Neu zuweisen",
          p: "Eine Variable ist nicht fest an einen Typ gebunden — du kannst ihr jederzeit einen neuen Wert zuweisen, auch mit anderem Datentyp. Python passt sich dabei automatisch an.",
          code: 'x = 5\nx = "fünf"\nprint(x)',
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Welchen Datentyp hat der Wert in x = 5?",
          code: "x = 5",
          opts: ["int", "float", "str", "bool"],
          a: 0,
          ex: "Ganze Zahlen ohne Nachkommastellen sind vom Typ int.",
        },
        {
          t: "mc",
          q: "Welchen Datentyp hat der Wert in preis = 3.99?",
          code: "preis = 3.99",
          opts: ["int", "float", "str", "bool"],
          a: 1,
          ex: "Zahlen mit Nachkommastellen sind vom Typ float.",
        },
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: 'name = "Simon"\nprint(name)',
          accept: ["Simon"],
          ex: "Der Variablenname wird beim print()-Aufruf durch den gespeicherten Wert ersetzt.",
        },
        {
          t: "fill",
          q: "Vervollständige die Zuweisung, die x den Wert 10 gibt:",
          code: "___ = 10",
          accept: ["x"],
          ex: "Variablennamen stehen links vom Gleichheitszeichen, der Wert steht rechts.",
        },
        {
          t: "mc",
          q: "Was passiert, wenn du nach x = 5 die Zeile x = \"text\" schreibst?",
          code: 'x = 5\nx = "text"',
          opts: [
            "Fehler, weil sich der Typ ändert",
            "x ist jetzt vom Typ str",
            "Python behält zusätzlich den alten Wert 5",
            "Beides ist gleichzeitig in x gespeichert",
          ],
          a: 1,
          ex: "Python ist dynamisch typisiert — eine Variable kann jederzeit neu zugewiesen werden, auch mit einem anderen Typ.",
        },
        {
          t: "build",
          q: "Erstelle eine Variable stadt mit dem Wert 'Berlin' und gib sie aus.",
          starter: "",
          check: { stdout: ["Berlin"] },
          hints: [
            "Eine Variable entsteht durch Zuweisung mit =.",
            "Nutze print() mit dem Variablennamen, nicht mit dem Text direkt.",
            'stadt = "Berlin"\nprint(stadt)',
          ],
          loesung: 'stadt = "Berlin"\nprint(stadt)',
          ex: "Eine Variable speichert einen Wert unter einem Namen, den du beliebig oft wiederverwenden kannst.",
        },
        {
          t: "build",
          q: "Erstelle drei Variablen name (str), alter (int) und groesse (float) mit sinnvollen Werten und gib jede einzeln aus.",
          starter: "",
          check: { stdout: ["Simon", "21", "1.85"] },
          hints: [
            "Drei Zuweisungen, dann drei print()-Aufrufe.",
            "name bekommt Anführungszeichen, alter und groesse nicht.",
            'name = "Simon"\nalter = 21\ngroesse = 1.85\nprint(name)\nprint(alter)\nprint(groesse)',
          ],
          loesung: 'name = "Simon"\nalter = 21\ngroesse = 1.85\nprint(name)\nprint(alter)\nprint(groesse)',
          ex: "Verschiedene Variablen können unterschiedliche Datentypen tragen, völlig unabhängig voneinander.",
        },
        {
          t: "build",
          q: "Weise x zuerst den Wert 5 zu und gib ihn aus, weise dann x den Text 'fünf' zu und gib ihn erneut aus.",
          starter: "",
          check: { stdout: ["5", "fünf"] },
          hints: [
            "Zwei Zuweisungen an dieselbe Variable x, dazwischen ein print().",
            "Zuerst der int-Wert, dann die Neuzuweisung als String.",
            'x = 5\nprint(x)\nx = "fünf"\nprint(x)',
          ],
          loesung: 'x = 5\nprint(x)\nx = "fünf"\nprint(x)',
          ex: "Variablen in Python sind nicht an einen festen Typ gebunden — eine Neuzuweisung überschreibt Wert und Typ gleichzeitig.",
        },
        {
          t: "build",
          q: "Gib den Datentyp (mit type()) von drei Variablen aus: einer int, einer float und einer str.",
          starter: "",
          check: { stdout: ["<class 'int'>", "<class 'float'>", "<class 'str'>"] },
          hints: [
            "type() zeigt den Datentyp eines Werts an.",
            "Erstelle drei Variablen mit passenden Werten, dann je ein print(type(...)).",
            'a = 1\nb = 2.5\nc = "x"\nprint(type(a))\nprint(type(b))\nprint(type(c))',
          ],
          loesung: 'a = 1\nb = 2.5\nc = "x"\nprint(type(a))\nprint(type(b))\nprint(type(c))',
          ex: "type() ist das Werkzeug, um im Zweifel nachzuschauen, welchen Datentyp ein Wert wirklich hat.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Kommentare aus Lektion 1. Erstelle eine Variable lieblingszahl mit einer Zahl deiner Wahl, kommentiere die Zeile darüber mit einer kurzen Erklärung, und gib die Variable aus.",
          starter: "",
          check: { stdout: ["7"] },
          hints: [
            "Ein Kommentar mit # beschreibt, was als Nächstes passiert.",
            "Danach eine ganz normale Zuweisung und ein print().",
            '# Meine Lieblingszahl\nlieblingszahl = 7\nprint(lieblingszahl)',
          ],
          loesung: '# Meine Lieblingszahl\nlieblingszahl = 7\nprint(lieblingszahl)',
          ex: "Variablen und Kommentare zusammen machen Code selbsterklärend — Kommentare beschreiben die Absicht hinter der Zuweisung.",
        },
      ],
      lernlog: [
        "Variablen speichern Werte unter einem Namen",
        "= weist einen Wert zu (ist keine Gleichheitsprüfung)",
        "int, float, str und bool sind die Grund-Datentypen",
        "type() zeigt den Datentyp eines Werts an",
        "Variablen können jederzeit neu zugewiesen werden, auch mit anderem Typ",
        "Variablennamen sollten sprechend sein",
      ],
    },

    // ───────────────────────────────────────────── L3: Zahlen & Operatoren
    {
      id: "t1l3",
      titel: "Zahlen & Operatoren",
      icon: "➗",
      farbe: "var(--lime)",
      kurz: "Rechnen wie ein Profi.",
      slides: [
        {
          h: "Grundrechenarten",
          p: "<code>+</code>, <code>-</code>, <code>*</code> und <code>/</code> funktionieren wie erwartet. Wichtig: <code>/</code> gibt immer ein float zurück, auch wenn das Ergebnis glatt aufgeht.",
          code: "print(10 / 2)",
        },
        {
          h: "// und %",
          p: "<code>//</code> ist die ganzzahlige Division (rundet ab), <code>%</code> liefert den Rest einer Division. Zusammen zerlegen sie eine Zahl in 'volle Gruppen' und 'Rest'.",
          code: "print(7 // 2)\nprint(7 % 2)",
        },
        {
          h: "** und == vs =",
          p: "<code>**</code> ist der Potenz-Operator. Verwechsle <code>=</code> (Zuweisung) nicht mit <code>==</code> (Vergleich auf Gleichheit) — einer der häufigsten Anfängerfehler.",
          code: "print(2 ** 3)\nprint(2 == 2)",
        },
      ],
      aufgaben: [
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: "print(7 // 2)",
          accept: ["3"],
          ex: "// rundet das Ergebnis der Division ab (floor division).",
        },
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: "print(7 % 2)",
          accept: ["1"],
          ex: "% liefert den Rest, der bei der Division übrig bleibt.",
        },
        {
          t: "mc",
          q: "Was gibt print(2 ** 3) aus?",
          code: "print(2 ** 3)",
          opts: ["6", "8", "9", "5"],
          a: 1,
          ex: "** ist der Potenz-Operator: 2 ** 3 bedeutet 2 * 2 * 2 = 8.",
        },
        {
          t: "mc",
          q: "Was ist der Unterschied zwischen = und ==?",
          opts: [
            "== weist zu, = vergleicht",
            "Beide sind identisch",
            "== vergleicht auf Gleichheit, = weist zu",
            "== funktioniert nur mit Strings",
          ],
          a: 2,
          ex: "= ist eine Zuweisung, == ist ein Vergleich — eine der häufigsten Verwechslungen beim Einstieg.",
        },
        {
          t: "fill",
          q: "Vervollständige den Vergleich, der prüft, ob x gleich 5 ist:",
          code: "x ___ 5",
          accept: ["=="],
          ex: "Ein doppeltes Gleichheitszeichen prüft auf Gleichheit, ohne dabei etwas zuzuweisen.",
        },
        {
          t: "build",
          q: "Berechne 12 + 8 und gib das Ergebnis aus.",
          starter: "",
          check: { stdout: ["20"] },
          hints: [
            "Grundrechenarten funktionieren direkt in print().",
            "print() kann einen ganzen Rechenausdruck als Argument bekommen.",
            "print(12 + 8)",
          ],
          loesung: "print(12 + 8)",
          ex: "Python wertet den Ausdruck zuerst aus und übergibt dann das Ergebnis an print().",
        },
        {
          t: "build",
          q: "Gib das Ergebnis von 17 // 5 und 17 % 5 jeweils in einer eigenen Zeile aus.",
          starter: "",
          check: { stdout: ["3", "2"] },
          hints: [
            "Zwei print()-Aufrufe, einer für //, einer für %.",
            "17 // 5 ist die Anzahl voller 5er-Gruppen, 17 % 5 der Rest.",
            "print(17 // 5)\nprint(17 % 5)",
          ],
          loesung: "print(17 // 5)\nprint(17 % 5)",
          ex: "// liefert den ganzzahligen Anteil, % den Rest — beide zusammen ergeben wieder die Ausgangszahl (3*5 + 2 = 17).",
        },
        {
          t: "build",
          q: "Prüfe, ob 9 gleich 3 ** 2 ist, und gib das Ergebnis (True/False) aus.",
          starter: "",
          check: { stdout: ["True"] },
          hints: [
            "Nutze == für den Vergleich, nicht =.",
            "** wird vor == berechnet.",
            "print(9 == 3 ** 2)",
          ],
          loesung: "print(9 == 3 ** 2)",
          ex: "** wird vor == ausgewertet (Punkt-vor-Strich gilt auch hier), deshalb wird zuerst 3 ** 2 berechnet und dann verglichen.",
        },
        {
          t: "build",
          q: "Berechne, wie viele volle 5er-Gruppen in 23 Personen passen und wie viele Personen übrig bleiben — je eine eigene Ausgabezeile.",
          starter: "",
          check: { stdout: ["4", "3"] },
          hints: [
            "// gibt die Anzahl voller Gruppen, % den Rest.",
            "Beide Operatoren beziehen sich auf dieselben zwei Zahlen: 23 und 5.",
            "print(23 // 5)\nprint(23 % 5)",
          ],
          loesung: "print(23 // 5)\nprint(23 % 5)",
          ex: "// und % sind das Standardwerkzeug, um eine Menge in gleich große Gruppen mit Rest aufzuteilen.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Variablen aus Lektion 2. Speichere zwei Zahlen in Variablen a und b, gib a hoch b aus und prüfe, ob das Ergebnis größer als 100 ist.",
          starter: "",
          check: { stdout: ["128", "True"] },
          hints: [
            "Wähle a und b so, dass a ** b eine Zahl über 100 ergibt.",
            "Nutze ** für die Potenz und > für den Vergleich.",
            "a = 2\nb = 7\nprint(a ** b)\nprint(a ** b > 100)",
          ],
          loesung: "a = 2\nb = 7\nprint(a ** b)\nprint(a ** b > 100)",
          ex: "Operatoren lassen sich beliebig mit Variablen und Vergleichen kombinieren — Python wertet auch hier zuerst ** und dann > aus.",
        },
      ],
      lernlog: [
        "+, -, *, / sind die Grundrechenarten, / gibt immer ein float zurück",
        "// rundet das Divisionsergebnis ab (ganzzahlige Division)",
        "% liefert den Rest einer Division",
        "** ist der Potenz-Operator",
        "= weist einen Wert zu, == vergleicht auf Gleichheit",
        "Operatoren lassen sich mit Variablen und Vergleichen kombinieren",
      ],
    },

    // ───────────────────────────────────────────── L4: Strings
    {
      id: "t1l4",
      titel: "Strings",
      icon: "🔤",
      farbe: "var(--orange)",
      kurz: "Text zerlegen und formatieren.",
      slides: [
        {
          h: "f-Strings",
          p: "Ein f-String (<code>f\"...\"</code>) bettet Variablen direkt in Text ein: alles in geschweiften Klammern <code>{ }</code> wird durch seinen Wert ersetzt. Das ist lesbarer als Strings mit + zu verketten.",
          code: 'name = "Simon"\nprint(f"Hallo {name}")',
        },
        {
          h: "String-Methoden & len()",
          p: "<code>.upper()</code> wandelt einen String in Großbuchstaben um (<code>.lower()</code> entsprechend in Kleinbuchstaben), ohne das Original zu verändern. <code>len()</code> zählt die Anzahl der Zeichen.",
          code: 'wort = "python"\nprint(wort.upper())\nprint(len(wort))',
        },
        {
          h: "Index",
          p: "Jedes Zeichen eines Strings hat eine Position, beginnend bei <code>0</code>. Negative Indizes zählen vom Ende: <code>-1</code> ist das letzte Zeichen.",
          code: 'wort = "Python"\nprint(wort[0])\nprint(wort[-1])',
        },
      ],
      aufgaben: [
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: 'name = "Simon"\nprint(f"Hallo {name}")',
          accept: ["Hallo Simon"],
          ex: "In einem f-String wird der Ausdruck in {} durch seinen aktuellen Wert ersetzt.",
        },
        {
          t: "mc",
          q: "Was gibt 'python'.upper() zurück?",
          code: "'python'.upper()",
          opts: ["python", "PYTHON", "Python", "Fehler"],
          a: 1,
          ex: ".upper() wandelt alle Buchstaben eines Strings in Großbuchstaben um.",
        },
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: 'wort = "Katze"\nprint(len(wort))',
          accept: ["5"],
          ex: "len() zählt die Anzahl der Zeichen im String.",
        },
        {
          t: "fill",
          q: "Vervollständige, um den ersten Buchstaben von wort auszugeben:",
          code: 'wort = "Katze"\nprint(wort[___])',
          accept: ["0"],
          ex: "Der erste Index eines Strings ist immer 0.",
        },
        {
          t: "mc",
          q: "Was gibt wort[-1] bei wort = \"Katze\" zurück?",
          code: 'wort = "Katze"\nprint(wort[-1])',
          opts: ["K", "a", "e", "Fehler"],
          a: 2,
          ex: "Negative Indizes zählen vom Ende: -1 ist immer das letzte Zeichen.",
        },
        {
          t: "build",
          q: "Erstelle eine Variable stadt mit 'Berlin' und gib mit einem f-String 'Ich wohne in Berlin' aus.",
          starter: "",
          check: { stdout: ["Ich wohne in Berlin"] },
          hints: [
            "Ein f-String beginnt mit f vor den Anführungszeichen.",
            "Die Variable kommt in geschweifte Klammern.",
            'stadt = "Berlin"\nprint(f"Ich wohne in {stadt}")',
          ],
          loesung: 'stadt = "Berlin"\nprint(f"Ich wohne in {stadt}")',
          ex: "f-Strings sind die lesbarste Art, Variablen in Text einzubetten.",
        },
        {
          t: "build",
          q: "Erstelle eine Variable wort mit 'python' und gib sie in Großbuchstaben aus.",
          starter: "",
          check: { stdout: ["PYTHON"] },
          hints: [
            "Nutze eine Methode, die Kleinbuchstaben in Großbuchstaben umwandelt.",
            "Die Methode wird mit einem Punkt an die Variable gehängt.",
            'wort = "python"\nprint(wort.upper())',
          ],
          loesung: 'wort = "python"\nprint(wort.upper())',
          ex: ".upper() verändert den ursprünglichen String nicht, sondern gibt eine neue, umgewandelte Version zurück.",
        },
        {
          t: "build",
          q: "Gib die Länge des Wortes 'Programmieren' aus.",
          starter: "",
          check: { stdout: ["13"] },
          hints: [
            "len() zählt die Zeichen eines Strings.",
            "Speichere das Wort zuerst in einer Variable.",
            'wort = "Programmieren"\nprint(len(wort))',
          ],
          loesung: 'wort = "Programmieren"\nprint(len(wort))',
          ex: "len() funktioniert nicht nur bei Strings, sondern überall dort, wo es etwas zu zählen gibt — z. B. bei Listen.",
        },
        {
          t: "build",
          q: "Gib den ersten und den letzten Buchstaben von 'Python' aus, jeweils in einer eigenen Zeile.",
          starter: "",
          check: { stdout: ["P", "n"] },
          hints: [
            "Der erste Index ist 0, der letzte ist -1.",
            "Zwei print()-Aufrufe mit jeweils einem Index.",
            'wort = "Python"\nprint(wort[0])\nprint(wort[-1])',
          ],
          loesung: 'wort = "Python"\nprint(wort[0])\nprint(wort[-1])',
          ex: "wort[0] ist das erste, wort[-1] das letzte Zeichen — negative Indizes ersparen dir, len(wort) - 1 auszurechnen.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Operatoren aus Lektion 3. Gib mit einem f-String aus, wie viele Buchstaben das Wort 'Elefant' hat, im Format 'Elefant hat 7 Buchstaben'.",
          starter: "",
          check: { stdout: ["Elefant hat 7 Buchstaben"] },
          hints: [
            "len(wort) kannst du direkt in einen f-String einsetzen.",
            "Der f-String braucht zwei {}-Platzhalter: einmal das Wort, einmal len(wort).",
            'wort = "Elefant"\nprint(f"{wort} hat {len(wort)} Buchstaben")',
          ],
          loesung: 'wort = "Elefant"\nprint(f"{wort} hat {len(wort)} Buchstaben")',
          ex: "f-Strings können auch das Ergebnis von Funktionsaufrufen wie len() direkt einbetten, nicht nur einfache Variablen.",
        },
      ],
      lernlog: [
        "f-Strings betten Variablen mit {} direkt in Text ein",
        ".upper() und .lower() wandeln Groß-/Kleinschreibung um, ohne das Original zu verändern",
        "len() gibt die Anzahl der Zeichen eines Strings zurück",
        "Strings werden über Indizes angesprochen, beginnend bei 0",
        "Negative Indizes zählen vom Ende des Strings (-1 = letztes Zeichen)",
        "Methoden wie .upper() werden mit einem Punkt an den String gehängt",
      ],
    },

    // ───────────────────────────────────────────── L5: input() & Typumwandlung
    {
      id: "t1l5",
      titel: "input() & Typumwandlung",
      icon: "⌨",
      farbe: "var(--violet)",
      kurz: "Mit dem Nutzer sprechen.",
      slides: [
        {
          h: "input() liest Eingaben",
          p: "<code>input()</code> pausiert das Programm, bis der Nutzer etwas eingibt und Enter drückt. Der eingegebene Wert kommt als Ergebnis zurück und wird meist direkt in einer Variable gespeichert.",
          code: 'name = input()\nprint(f"Hallo {name}")',
        },
        {
          h: "input() liefert immer einen String",
          p: "Auch wenn der Nutzer eine Zahl eintippt, ist das Ergebnis von <code>input()</code> immer ein <code>str</code>. Ohne Umwandlung kannst du damit nicht rechnen.",
          code: 'zahl = input()\nprint(type(zahl))',
        },
        {
          h: "Typumwandlung",
          p: "<code>int()</code> und <code>float()</code> wandeln einen String in eine Zahl um, <code>str()</code> umgekehrt eine Zahl in Text. Ein ungültiger String wie <code>int(\"Hallo\")</code> löst einen <code>ValueError</code> aus.",
          code: 'alter = int(input())\nprint(alter + 1)',
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Welchen Datentyp gibt input() immer zurück?",
          opts: ["int", "str", "float", "hängt von der Eingabe ab"],
          a: 1,
          ex: "input() liefert IMMER einen String zurück, egal was der Nutzer eintippt.",
        },
        {
          t: "out",
          q: "Was gibt dieser Code aus, wenn '5' eingegeben wird?",
          code: 'zahl = input()\nprint(type(zahl))',
          accept: ["<class 'str'>"],
          ex: "Auch eine eingegebene Zahl bleibt zunächst ein String, bis sie explizit umgewandelt wird.",
        },
        {
          t: "fill",
          q: "Vervollständige, um die Eingabe in eine Ganzzahl umzuwandeln:",
          code: "zahl = ___(input())\nprint(zahl + 1)",
          accept: ["int"],
          ex: "int() wandelt einen String in eine Ganzzahl um — erst danach kann man damit rechnen.",
        },
        {
          t: "mc",
          q: "Was passiert bei int(input()), wenn 'Hallo' eingegeben wird?",
          opts: ["gibt 0 zurück", "ValueError", "wird zu 'Hallo' als int gespeichert", "funktioniert trotzdem normal"],
          a: 1,
          ex: "int() kann nur echte Zahl-Strings umwandeln — sonst gibt es einen ValueError.",
        },
        {
          t: "out",
          q: "Was gibt das aus, wenn 3.5 eingegeben wird?",
          code: "x = float(input())\nprint(x + 1)",
          accept: ["4.5"],
          ex: "float() wandelt in eine Kommazahl um, danach ist normales Rechnen möglich.",
        },
        {
          t: "build",
          q: "Frage nach dem Namen des Nutzers mit input() und gib 'Hallo, <Name>!' aus.",
          starter: "",
          check: { stdout: ["Hallo, Simon!"], stdin: ["Simon"] },
          hints: [
            "input() ohne Argumente liest eine Zeile Text.",
            "Nutze einen f-String, um den Namen einzubauen.",
            'name = input()\nprint(f"Hallo, {name}!")',
          ],
          loesung: 'name = input()\nprint(f"Hallo, {name}!")',
          ex: "input() pausiert das Programm, bis der Nutzer Enter drückt — danach geht es mit dem eingegebenen Wert weiter.",
        },
        {
          t: "build",
          q: "Frage nach dem Alter (als Zahl) und gib aus, wie alt die Person in 10 Jahren sein wird.",
          starter: "",
          check: { stdout: ["30"], stdin: ["20"] },
          hints: [
            "Die Eingabe muss erst in eine Zahl umgewandelt werden.",
            "int(input()) statt nur input().",
            'alter = int(input())\nprint(alter + 10)',
          ],
          loesung: 'alter = int(input())\nprint(alter + 10)',
          ex: "Ohne int() würde alter + 10 einen Fehler werfen, weil man einen String nicht zu einer Zahl addieren kann.",
        },
        {
          t: "build",
          q: "Frage nach zwei Zahlen (je eine eigene input()-Zeile) und gib ihre Summe aus.",
          starter: "",
          check: { stdout: ["9"], stdin: ["4", "5"] },
          hints: [
            "Zwei separate int(input())-Aufrufe, in zwei Variablen gespeichert.",
            "Danach die beiden Variablen addieren und ausgeben.",
            'a = int(input())\nb = int(input())\nprint(a + b)',
          ],
          loesung: 'a = int(input())\nb = int(input())\nprint(a + b)',
          ex: "Jeder input()-Aufruf holt eine neue Zeile aus der Eingabe — bei zwei Aufrufen bekommst du zwei unterschiedliche Werte.",
        },
        {
          t: "build",
          q: "Frage nach einem Preis (mit Nachkommastellen) und gib den Preis inklusive 20% Aufschlag aus.",
          starter: "",
          check: { stdout: ["12.0"], stdin: ["10"] },
          hints: [
            "Nutze float() statt int(), weil Nachkommastellen möglich sind.",
            "20% Aufschlag heißt: mit 1.2 multiplizieren.",
            'preis = float(input())\nprint(preis * 1.2)',
          ],
          loesung: 'preis = float(input())\nprint(preis * 1.2)',
          ex: "float() ist nötig, sobald mit Nachkommastellen gerechnet wird — int() würde sie abschneiden oder sogar crashen.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Strings aus Lektion 4. Frage nach dem Namen und gib mit einem f-String aus, wie viele Buchstaben er hat, im Format 'Simon hat 5 Buchstaben'.",
          starter: "",
          check: { stdout: ["Simon hat 5 Buchstaben"], stdin: ["Simon"] },
          hints: [
            "input() gibt bereits einen String zurück — len() funktioniert direkt darauf.",
            "Baue einen f-String mit zwei Platzhaltern: dem Namen und len(name).",
            'name = input()\nprint(f"{name} hat {len(name)} Buchstaben")',
          ],
          loesung: 'name = input()\nprint(f"{name} hat {len(name)} Buchstaben")',
          ex: "input() gibt bereits einen String zurück — len() funktioniert direkt darauf, ganz ohne Umwandlung.",
        },
      ],
      lernlog: [
        "input() liest eine Zeile Text von der Konsole",
        "input() gibt IMMER einen String zurück",
        "int() und float() wandeln Strings in Zahlen um",
        "Ungültige Umwandlungen (z. B. int(\"Hallo\")) lösen einen ValueError aus",
        "Erst nach der Umwandlung kann man mit der Eingabe rechnen",
        "str() wandelt umgekehrt Zahlen in Strings um",
      ],
    },

    // ───────────────────────────────────────────── L6: if / elif / else
    {
      id: "t1l6",
      titel: "if / elif / else",
      icon: "🔀",
      farbe: "var(--red)",
      kurz: "Entscheidungen treffen.",
      slides: [
        {
          h: "if prüft eine Bedingung",
          p: "<code>if</code> führt den eingerückten Block nur aus, wenn die Bedingung wahr ist. Vergleichsoperatoren wie <code>&gt;</code>, <code>&lt;</code>, <code>==</code> und <code>!=</code> liefern dabei True oder False.",
          code: 'x = 5\nif x > 3:\n    print("groß")',
        },
        {
          h: "elif und else",
          p: "<code>elif</code> prüft eine weitere Bedingung, falls die vorherige falsch war — beliebig oft wiederholbar. <code>else</code> fängt am Ende alle übrigen Fälle auf.",
          code: 'x = 0\nif x > 0:\n    print("positiv")\nelif x < 0:\n    print("negativ")\nelse:\n    print("null")',
        },
        {
          h: "and, or, not",
          p: "<code>and</code> verlangt, dass beide Seiten wahr sind, <code>or</code> reicht schon eine wahre Seite, <code>not</code> kehrt einen Wahrheitswert um. Damit lassen sich mehrere Bedingungen kombinieren.",
          code: 'alter = 25\nprint(alter > 18 and alter < 65)',
        },
      ],
      aufgaben: [
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: 'x = 5\nif x > 3:\n    print("groß")\nelse:\n    print("klein")',
          accept: ["groß"],
          ex: "Da 5 > 3 wahr ist, wird der if-Block ausgeführt und der else-Block übersprungen.",
        },
        {
          t: "mc",
          q: "Wie viele elif-Blöcke darf ein if maximal haben?",
          opts: ["genau einen", "maximal drei", "beliebig viele", "keinen"],
          a: 2,
          ex: "elif kann beliebig oft wiederholt werden, um mehrere Bedingungen nacheinander zu prüfen.",
        },
        {
          t: "fill",
          q: "Vervollständige die Bedingung: nur wenn x größer als 0 UND kleiner als 10 ist:",
          code: "if x > 0 ___ x < 10:",
          accept: ["and"],
          ex: "and verlangt, dass beide Bedingungen gleichzeitig wahr sind.",
        },
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: "x = 5\nprint(x > 3 or x > 100)",
          accept: ["True"],
          ex: "Bei or reicht es, wenn eine der beiden Bedingungen wahr ist — hier ist x > 3 bereits wahr.",
        },
        {
          t: "mc",
          q: "Was gibt not (5 > 3) zurück?",
          code: "print(not (5 > 3))",
          opts: ["True", "False", "5", "Fehler"],
          a: 1,
          ex: "not kehrt einen Wahrheitswert um: aus True wird False.",
        },
        {
          t: "build",
          q: "Prüfe, ob die Zahl 7 größer als 5 ist, und gib 'ja' oder 'nein' aus.",
          starter: "",
          check: { stdout: ["ja"] },
          hints: [
            "Nutze if und else für zwei sich ausschließende Fälle.",
            "Die Bedingung ist ein einfacher Vergleich mit >.",
            'if 7 > 5:\n    print("ja")\nelse:\n    print("nein")',
          ],
          loesung: 'if 7 > 5:\n    print("ja")\nelse:\n    print("nein")',
          ex: "if/else deckt genau zwei sich ausschließende Fälle ab — es wird immer genau einer davon ausgeführt.",
        },
        {
          t: "build",
          q: "Frage nach einer Zahl und gib 'positiv', 'negativ' oder 'null' aus, je nachdem was zutrifft.",
          starter: "",
          check: { stdout: ["negativ"], stdin: ["-3"] },
          hints: [
            "Drei sich ausschließende Fälle brauchen if, elif und else.",
            "Prüfe zuerst > 0, dann < 0, der Rest ist automatisch 0.",
            'zahl = int(input())\nif zahl > 0:\n    print("positiv")\nelif zahl < 0:\n    print("negativ")\nelse:\n    print("null")',
          ],
          loesung: 'zahl = int(input())\nif zahl > 0:\n    print("positiv")\nelif zahl < 0:\n    print("negativ")\nelse:\n    print("null")',
          ex: "elif prüft weitere Bedingungen erst, wenn die vorherige falsch war — am Ende wird genau eine Zeile ausgegeben.",
        },
        {
          t: "build",
          q: "Frage nach dem Alter und gib 'Zutritt erlaubt' aus, wenn die Person mindestens 18 ist, sonst 'Zutritt verweigert'.",
          starter: "",
          check: { stdout: ["Zutritt verweigert"], stdin: ["16"] },
          hints: [
            "'Mindestens 18' heißt >=, nicht nur >.",
            "Ein einfaches if/else reicht hier.",
            'alter = int(input())\nif alter >= 18:\n    print("Zutritt erlaubt")\nelse:\n    print("Zutritt verweigert")',
          ],
          loesung: 'alter = int(input())\nif alter >= 18:\n    print("Zutritt erlaubt")\nelse:\n    print("Zutritt verweigert")',
          ex: ">= schließt den Grenzwert 18 selbst mit ein — ein reines > würde 18-Jährige fälschlich ausschließen.",
        },
        {
          t: "build",
          q: "Frage nach einer Zahl und gib 'im Bereich' aus, wenn sie zwischen 10 und 20 (beide eingeschlossen) liegt, sonst 'außerhalb'.",
          starter: "",
          check: { stdout: ["im Bereich"], stdin: ["15"] },
          hints: [
            "Zwei Bedingungen müssen gleichzeitig gelten — das ist der Fall für and.",
            "zahl >= 10 and zahl <= 20",
            'zahl = int(input())\nif zahl >= 10 and zahl <= 20:\n    print("im Bereich")\nelse:\n    print("außerhalb")',
          ],
          loesung: 'zahl = int(input())\nif zahl >= 10 and zahl <= 20:\n    print("im Bereich")\nelse:\n    print("außerhalb")',
          ex: "and kombiniert zwei Grenzwerte zu einem einzigen Bereichs-Check.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Zahlen & Operatoren aus Lektion 3 und input() aus Lektion 5. Frage nach einer Zahl und gib aus, ob sie gerade oder ungerade ist.",
          starter: "",
          check: { stdout: ["gerade"], stdin: ["4"] },
          hints: [
            "Der Rest bei Division durch 2 verrät die Geradzahligkeit.",
            "zahl % 2 == 0 ist die Standard-Prüfung.",
            'zahl = int(input())\nif zahl % 2 == 0:\n    print("gerade")\nelse:\n    print("ungerade")',
          ],
          loesung: 'zahl = int(input())\nif zahl % 2 == 0:\n    print("gerade")\nelse:\n    print("ungerade")',
          ex: "% 2 == 0 ist die Standard-Prüfung für Geradzahligkeit — der Rest bei Division durch 2 ist immer entweder 0 oder 1.",
        },
      ],
      lernlog: [
        "if prüft eine Bedingung und führt den eingerückten Block nur bei True aus",
        "elif prüft weitere Bedingungen, wenn die vorherige falsch war",
        "else fängt alle übrigen Fälle auf",
        "and verlangt, dass beide Seiten wahr sind",
        "or verlangt, dass mindestens eine Seite wahr ist",
        "not kehrt einen Wahrheitswert um",
        "Einrückung bestimmt, was zu einem Block gehört",
      ],
    },

    // ───────────────────────────────────────────── L7: Listen
    {
      id: "t1l7",
      titel: "Listen",
      icon: "📋",
      farbe: "var(--teal)",
      kurz: "Mehrere Werte, eine Variable.",
      slides: [
        {
          h: "Was ist eine Liste?",
          p: "Eine Liste speichert mehrere Werte in einer festen Reihenfolge. Sie wird mit eckigen Klammern erstellt, Elemente durch Komma getrennt. Zugriff auf ein Element erfolgt über den Index, beginnend bei 0.",
          code: 'zahlen = [10, 20, 30]\nprint(zahlen[1])',
        },
        {
          h: "append() und len()",
          p: "<code>.append()</code> hängt ein neues Element ans Ende der Liste an — die Liste wird dabei direkt verändert. <code>len()</code> gibt die Anzahl der Elemente zurück.",
          code: 'liste = [1, 2]\nliste.append(3)\nprint(len(liste))',
        },
        {
          h: "Negativer Index",
          p: "Wie bei Strings zählt ein negativer Index vom Ende der Liste: <code>-1</code> ist das letzte Element. Das erspart dir, <code>len(liste) - 1</code> auszurechnen.",
          code: 'liste = [1, 2, 3]\nprint(liste[-1])',
        },
      ],
      aufgaben: [
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: "zahlen = [10, 20, 30]\nprint(zahlen[1])",
          accept: ["20"],
          ex: "Listen sind nullbasiert — Index 1 ist das zweite Element.",
        },
        {
          t: "mc",
          q: "Was macht liste.append(4)?",
          opts: [
            "fügt 4 am Anfang der Liste ein",
            "ersetzt das erste Element durch 4",
            "fügt 4 am Ende der Liste hinzu",
            "löscht 4 aus der Liste",
          ],
          a: 2,
          ex: "append() hängt ein Element ans Ende der Liste an, sie wird dabei direkt verändert.",
        },
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: "liste = [1, 2, 3]\nprint(len(liste))",
          accept: ["3"],
          ex: "len() zählt die Anzahl der Elemente in der Liste.",
        },
        {
          t: "fill",
          q: "Vervollständige, um das letzte Element auszugeben:",
          code: "liste = [1, 2, 3]\nprint(liste[___])",
          accept: ["-1"],
          ex: "Index -1 ist immer das letzte Element, egal wie lang die Liste ist.",
        },
        {
          t: "mc",
          q: "Was gibt [1, 2, 3][0] zurück?",
          code: "print([1, 2, 3][0])",
          opts: ["1", "2", "3", "Fehler"],
          a: 0,
          ex: "Der erste Index einer Liste ist 0.",
        },
        {
          t: "build",
          q: "Erstelle eine Liste farben mit den Einträgen 'rot', 'grün', 'blau' und gib das erste Element aus.",
          starter: "",
          check: { stdout: ["rot"] },
          hints: [
            "Eine Liste wird mit eckigen Klammern erstellt, Elemente durch Komma getrennt.",
            "Zugriff auf das erste Element mit Index 0.",
            'farben = ["rot", "grün", "blau"]\nprint(farben[0])',
          ],
          loesung: 'farben = ["rot", "grün", "blau"]\nprint(farben[0])',
          ex: "Listen bündeln mehrere zusammengehörige Werte in einer geordneten Reihenfolge.",
        },
        {
          t: "build",
          q: "Erstelle eine leere Liste, füge 'Apfel' und 'Birne' mit append() hinzu und gib die ganze Liste aus.",
          starter: "",
          check: { stdout: ["['Apfel', 'Birne']"] },
          hints: [
            "Eine leere Liste entsteht mit [].",
            "append() fügt jeweils ein Element ans Ende an.",
            'einkauf = []\neinkauf.append("Apfel")\neinkauf.append("Birne")\nprint(einkauf)',
          ],
          loesung: 'einkauf = []\neinkauf.append("Apfel")\neinkauf.append("Birne")\nprint(einkauf)',
          ex: "append() verändert die Liste direkt (in-place) — print() der ganzen Liste zeigt alle Elemente auf einmal.",
        },
        {
          t: "build",
          q: "Gib die Länge der Liste [3, 7, 1, 9, 2] aus, sowie das letzte Element über einen negativen Index.",
          starter: "",
          check: { stdout: ["5", "2"] },
          hints: [
            "len() gibt die Anzahl der Elemente zurück.",
            "liste[-1] ist das letzte Element.",
            'zahlen = [3, 7, 1, 9, 2]\nprint(len(zahlen))\nprint(zahlen[-1])',
          ],
          loesung: 'zahlen = [3, 7, 1, 9, 2]\nprint(len(zahlen))\nprint(zahlen[-1])',
          ex: "len() und negative Indizes ergänzen sich: zahlen[-1] entspricht immer zahlen[len(zahlen) - 1], nur kürzer.",
        },
        {
          t: "build",
          q: "Erstelle eine Liste mit den Zahlen 1 bis 5 und gib das zweite und das vorletzte Element aus.",
          starter: "",
          check: { stdout: ["2", "4"] },
          hints: [
            "Das zweite Element hat Index 1.",
            "Das vorletzte Element hat Index -2.",
            'zahlen = [1, 2, 3, 4, 5]\nprint(zahlen[1])\nprint(zahlen[-2])',
          ],
          loesung: 'zahlen = [1, 2, 3, 4, 5]\nprint(zahlen[1])\nprint(zahlen[-2])',
          ex: "Positive und negative Indizes lassen sich beliebig mischen, je nachdem was leichter zu zählen ist.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Zahlen & Operatoren aus Lektion 3. Erstelle eine Liste mit 6 Zahlen deiner Wahl und gib aus, ob die Anzahl der Elemente (len) gerade ist.",
          starter: "",
          check: { stdout: ["True"] },
          hints: [
            "len(liste) gibt eine ganz normale Zahl zurück.",
            "Prüfe mit % 2 == 0, ob diese Zahl gerade ist.",
            'zahlen = [1, 2, 3, 4, 5, 6]\nprint(len(zahlen) % 2 == 0)',
          ],
          loesung: 'zahlen = [1, 2, 3, 4, 5, 6]\nprint(len(zahlen) % 2 == 0)',
          ex: "len() liefert eine ganz normale Zahl — damit lässt sich genauso weiterrechnen wie mit jeder anderen Zahl.",
        },
      ],
      lernlog: [
        "Listen speichern mehrere Werte in einer geordneten Reihenfolge",
        "Zugriff auf Listenelemente über den Index, beginnend bei 0",
        "append() fügt ein Element ans Ende an und verändert die Liste direkt",
        "len() gibt die Anzahl der Elemente zurück",
        "Negative Indizes zählen vom Ende der Liste (-1 = letztes Element)",
        "Listen sind veränderlich (mutable), anders als Strings",
      ],
    },

    // ───────────────────────────────────────────── L8: Schleifen
    {
      id: "t1l8",
      titel: "Schleifen",
      icon: "🔁",
      farbe: "var(--gold)",
      kurz: "Wiederholen ohne Copy-Paste.",
      slides: [
        {
          h: "for und range()",
          p: "<code>for i in range(n)</code> wiederholt einen Block n-mal, i zählt dabei von 0 bis n-1. Eine for-Schleife kann auch direkt über eine Liste laufen.",
          code: 'for i in range(3):\n    print(i)',
        },
        {
          h: "while",
          p: "<code>while</code> wiederholt einen Block, solange eine Bedingung wahr ist. Anders als bei for musst du selbst dafür sorgen, dass sich die Bedingung irgendwann ändert — sonst läuft die Schleife endlos.",
          code: 'x = 0\nwhile x < 3:\n    print(x)\n    x = x + 1',
        },
        {
          h: "break",
          p: "<code>break</code> beendet eine Schleife sofort, egal was die Bedingung sagt. Nützlich, um eine Wiederholung abzubrechen, sobald ein bestimmter Zustand erreicht ist.",
          code: 'for i in range(10):\n    if i == 3:\n        break\n    print(i)',
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Wie oft läuft diese Schleife?",
          code: "for i in range(5):\n    print(i)",
          opts: ["4", "5", "6", "unendlich"],
          a: 1,
          ex: "range(5) erzeugt die Zahlen 0 bis 4 — das sind genau 5 Durchläufe.",
        },
        {
          t: "out",
          q: "Was gibt die letzte Ausgabe dieser Schleife aus?",
          code: "for i in range(3):\n    print(i)",
          accept: ["2"],
          ex: "range(3) zählt 0, 1, 2 — der letzte Wert ist also 2, nicht 3.",
        },
        {
          t: "fill",
          q: "Vervollständige, damit die Schleife 1 bis 5 (statt 0 bis 4) zählt:",
          code: "for i in range(1, ___):\n    print(i)",
          accept: ["6"],
          ex: "range(1, 6) erzeugt 1, 2, 3, 4, 5 — die Obergrenze ist immer exklusiv.",
        },
        {
          t: "mc",
          q: "Was macht break in einer Schleife?",
          opts: ["überspringt eine einzelne Iteration", "beendet die Schleife sofort", "startet die Schleife neu", "pausiert das Programm"],
          a: 1,
          ex: "break bricht die gesamte Schleife sofort ab, unabhängig davon, was die Bedingung sagt.",
        },
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: "x = 0\nwhile x < 3:\n    x = x + 1\nprint(x)",
          accept: ["3"],
          ex: "Die while-Schleife läuft, bis x < 3 falsch wird — das ist bei x = 3 der Fall, danach wird x ausgegeben.",
        },
        {
          t: "build",
          q: "Gib mit einer for-Schleife die Zahlen 1 bis 3 aus (jede in einer eigenen Zeile).",
          starter: "",
          check: { stdout: ["1", "2", "3"] },
          hints: [
            "range(1, 4) erzeugt genau 1, 2, 3.",
            "print() im Schleifenkörper, eingerückt.",
            "for i in range(1, 4):\n    print(i)",
          ],
          loesung: "for i in range(1, 4):\n    print(i)",
          ex: "range(1, 4) erzeugt exakt 1, 2, 3 — die Obergrenze zählt selbst nicht mehr mit.",
        },
        {
          t: "build",
          q: "Gib mit einer for-Schleife alle Zahlen von 1 bis 10 aus, die durch 3 teilbar sind.",
          starter: "",
          check: { stdout: ["3", "6", "9"] },
          hints: [
            "Kombiniere eine for-Schleife mit einem if.",
            "Teilbar durch 3 heißt: Rest bei Division durch 3 ist 0.",
            "for i in range(1, 11):\n    if i % 3 == 0:\n        print(i)",
          ],
          loesung: "for i in range(1, 11):\n    if i % 3 == 0:\n        print(i)",
          ex: "Schleife und if lassen sich kombinieren, um aus vielen Werten nur die passenden auszugeben.",
        },
        {
          t: "build",
          q: "Nutze eine while-Schleife, um von 5 herunter bis 1 zu zählen (je eine eigene Zeile).",
          starter: "",
          check: { stdout: ["5", "4", "3", "2", "1"] },
          hints: [
            "Die Bedingung lautet: solange x größer als 0 ist.",
            "Nach jedem print() muss x kleiner werden, sonst läuft die Schleife ewig.",
            "x = 5\nwhile x > 0:\n    print(x)\n    x = x - 1",
          ],
          loesung: "x = 5\nwhile x > 0:\n    print(x)\n    x = x - 1",
          ex: "Bei while-Schleifen musst du selbst dafür sorgen, dass sich die Bedingung irgendwann ändert — sonst läuft sie ewig.",
        },
        {
          t: "build",
          q: "Gib die Zahlen 1 bis 10 aus, breche die Schleife aber ab, sobald du bei 6 angekommen bist (6 selbst wird nicht mehr ausgegeben).",
          starter: "",
          check: { stdout: ["1", "2", "3", "4", "5"] },
          hints: [
            "Prüfe vor dem print(), ob die aktuelle Zahl 6 ist.",
            "break beendet die Schleife, bevor der print()-Aufruf für 6 erreicht wird.",
            "for i in range(1, 11):\n    if i == 6:\n        break\n    print(i)",
          ],
          loesung: "for i in range(1, 11):\n    if i == 6:\n        break\n    print(i)",
          ex: "break verlässt die Schleife sofort, bevor der print()-Aufruf für 6 überhaupt erreicht wird.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: Listen aus Lektion 7. Summiere alle Zahlen einer Liste mit einer Schleife — ohne sum().",
          starter: "",
          check: { stdout: ["15"] },
          hints: [
            "Starte mit einer Summen-Variable bei 0.",
            "Eine for-Schleife läuft direkt über die Liste, addiere jedes Element zur Summe.",
            "zahlen = [1, 2, 3, 4, 5]\nsumme = 0\nfor z in zahlen:\n    summe = summe + z\nprint(summe)",
          ],
          loesung: "zahlen = [1, 2, 3, 4, 5]\nsumme = 0\nfor z in zahlen:\n    summe = summe + z\nprint(summe)",
          ex: "Das Muster 'Ergebnis-Variable auf 0 setzen, dann in der Schleife hochzählen' ist der Grundbaustein für fast jede Aggregation.",
        },
      ],
      lernlog: [
        "for i in range(n) wiederholt einen Block n Mal",
        "for-Schleifen können auch direkt über Listen iterieren",
        "range(a, b) erzeugt Zahlen von a bis b-1 (b ist exklusiv)",
        "while wiederholt, solange eine Bedingung wahr ist",
        "while-Schleifen brauchen eine Änderung der Bedingung, sonst laufen sie endlos",
        "break beendet eine Schleife sofort, egal was die Bedingung sagt",
      ],
    },

    // ───────────────────────────────────────────── L9: Funktionen
    {
      id: "t1l9",
      titel: "Funktionen",
      icon: "🧩",
      farbe: "var(--blue)",
      kurz: "Code wiederverwendbar machen.",
      slides: [
        {
          h: "def definiert eine Funktion",
          p: "Mit <code>def</code> erstellst du eine Funktion: Name, Klammern, Doppelpunkt, dann der eingerückte Funktionskörper. Eine Funktion muss danach auch aufgerufen werden, sonst passiert nichts.",
          code: 'def begruesse():\n    print("Hallo!")\n\nbegruesse()',
        },
        {
          h: "Parameter",
          p: "Parameter sind Platzhalter in der Klammer, die beim Aufruf mit echten Werten (Argumenten) gefüllt werden. So funktioniert dieselbe Funktion für beliebig viele verschiedene Eingaben.",
          code: 'def quadrat(x):\n    return x ** 2\n\nprint(quadrat(4))',
        },
        {
          h: "return vs. print",
          p: "<code>return</code> gibt einen Wert an den Aufrufer zurück, mit dem das Programm weiterarbeiten kann. <code>print()</code> zeigt nur etwas im Terminal an, liefert aber keinen weiterverwendbaren Wert.",
          code: 'def addiere(a, b):\n    return a + b\n\nergebnis = addiere(2, 3)\nprint(ergebnis)',
        },
      ],
      aufgaben: [
        {
          t: "mc",
          q: "Wie definierst du eine Funktion namens gruesse?",
          opts: ["function gruesse():", "def gruesse():", "func gruesse():", "define gruesse():"],
          a: 1,
          ex: "def leitet eine Funktionsdefinition ein, gefolgt von Name, Klammern und Doppelpunkt.",
        },
        {
          t: "out",
          q: "Was gibt dieser Aufruf aus?",
          code: "def verdopple(x):\n    return x * 2\nprint(verdopple(5))",
          accept: ["10"],
          ex: "return gibt den Wert an den Aufrufer zurück, print() zeigt ihn dann im Terminal an.",
        },
        {
          t: "mc",
          q: "Was ist der Unterschied zwischen return und print in einer Funktion?",
          opts: [
            "kein Unterschied",
            "print gibt den Wert an den Aufrufer zurück, return zeigt ihn nur an",
            "return gibt den Wert an den Aufrufer zurück, print zeigt ihn nur im Terminal an",
            "beide beenden die Funktion sofort",
          ],
          a: 2,
          ex: "return liefert einen Wert, mit dem der Rest des Programms weiterarbeiten kann — print zeigt nur an, ohne einen Wert zurückzugeben.",
        },
        {
          t: "fill",
          q: "Vervollständige den Funktionsaufruf mit dem Argument 3:",
          code: "def quadrat(x):\n    return x ** 2\nprint(quadrat(___))",
          accept: ["3"],
          ex: "Der Wert in den Klammern beim Aufruf wird als Parameter x in die Funktion übergeben.",
        },
        {
          t: "out",
          q: "Was gibt dieser Code aus?",
          code: 'def gruss(name):\n    print(f"Hallo {name}")\ngruss("Anna")',
          accept: ["Hallo Anna"],
          ex: "Der Funktionskörper wird bei jedem Aufruf mit den übergebenen Argumenten neu ausgeführt.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion begruesse(), die 'Hallo!' ausgibt, und rufe sie auf.",
          starter: "",
          check: { stdout: ["Hallo!"] },
          hints: [
            "def begruesse(): leitet die Definition ein.",
            "Der Funktionskörper mit print() muss eingerückt sein.",
            "Nach der Definition muss die Funktion noch aufgerufen werden: begruesse()",
          ],
          loesung: 'def begruesse():\n    print("Hallo!")\n\nbegruesse()',
          ex: "Eine Funktion muss nach der Definition auch aufgerufen werden, sonst passiert bei der Ausführung nichts.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion quadrat(x), die das Quadrat von x per return zurückgibt (kein print in der Funktion). Rufe sie mit 4 auf und gib das Ergebnis mit print() aus.",
          starter: "",
          check: {
            stdout: ["16"],
            tests: "assert quadrat(3) == 9\nassert quadrat(0) == 0",
          },
          hints: [
            "Die Funktion selbst soll nichts ausgeben, nur zurückgeben (return).",
            "return x ** 2 ist das Quadrat von x.",
            "def quadrat(x):\n    return x ** 2\n\nprint(quadrat(4))",
          ],
          loesung: "def quadrat(x):\n    return x ** 2\n\nprint(quadrat(4))",
          ex: "return macht die Funktion wiederverwendbar — der Rückgabewert lässt sich weiterverarbeiten, nicht nur anzeigen.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion addiere(a, b), die die Summe zurückgibt. Rufe sie mit zwei Zahlen deiner Wahl auf und gib das Ergebnis aus.",
          starter: "",
          check: {
            stdout: ["7"],
            tests: "assert addiere(2, 2) == 4\nassert addiere(-1, 1) == 0",
          },
          hints: [
            "Zwei Parameter werden durch Komma getrennt: addiere(a, b).",
            "Die Reihenfolge beim Aufruf muss zur Definition passen.",
            "def addiere(a, b):\n    return a + b\n\nprint(addiere(3, 4))",
          ],
          loesung: "def addiere(a, b):\n    return a + b\n\nprint(addiere(3, 4))",
          ex: "Mehrere Parameter werden durch Komma getrennt — die Position beim Aufruf entscheidet, welcher Wert zu welchem Parameter gehört.",
        },
        {
          t: "build",
          q: "Schreibe eine Funktion ist_erwachsen(alter), die True zurückgibt, wenn alter >= 18 ist, sonst False. Rufe sie einmal auf und gib das Ergebnis aus.",
          starter: "",
          check: {
            stdout: ["True"],
            tests: "assert ist_erwachsen(18) == True\nassert ist_erwachsen(17) == False",
          },
          hints: [
            "Ein Vergleich wie alter >= 18 ist bereits ein bool-Wert.",
            "return alter >= 18 spart ein extra if.",
            "def ist_erwachsen(alter):\n    return alter >= 18\n\nprint(ist_erwachsen(20))",
          ],
          loesung: "def ist_erwachsen(alter):\n    return alter >= 18\n\nprint(ist_erwachsen(20))",
          ex: "Eine Bedingung als Ausdruck (alter >= 18) ist bereits ein bool-Wert — return alter >= 18 spart dir ein zusätzliches if.",
        },
        {
          t: "build",
          q: "🔗 nutzt auch: if/elif/else aus Lektion 6 und Schleifen aus Lektion 8. Schreibe zaehle_gerade(liste), die zurückgibt, wie viele gerade Zahlen die Liste enthält.",
          starter: "",
          check: {
            stdout: ["3"],
            tests:
              "assert zaehle_gerade([1, 2, 3, 4]) == 2\nassert zaehle_gerade([]) == 0\nassert zaehle_gerade([1, 3, 5]) == 0",
          },
          hints: [
            "Zähle mit einer Variable, die bei 0 startet.",
            "Eine for-Schleife über die Liste, mit if wird jede gerade Zahl gezählt.",
            "def zaehle_gerade(liste):\n    anzahl = 0\n    for zahl in liste:\n        if zahl % 2 == 0:\n            anzahl = anzahl + 1\n    return anzahl\n\nprint(zaehle_gerade([1, 2, 3, 4, 5, 6]))",
          ],
          loesung:
            "def zaehle_gerade(liste):\n    anzahl = 0\n    for zahl in liste:\n        if zahl % 2 == 0:\n            anzahl = anzahl + 1\n    return anzahl\n\nprint(zaehle_gerade([1, 2, 3, 4, 5, 6]))",
          ex: "Funktionen bündeln Schleife und Bedingung zu einem wiederverwendbaren Baustein — genau das macht sie so mächtig.",
        },
      ],
      lernlog: [
        "def definiert eine Funktion mit Name und Parametern",
        "Eine Funktion muss aufgerufen werden, um ausgeführt zu werden",
        "Parameter sind Platzhalter, die beim Aufruf mit echten Werten gefüllt werden",
        "return gibt einen Wert an den Aufrufer zurück, ohne ihn anzuzeigen",
        "print() zeigt nur an, gibt aber keinen Wert für die Weiterverarbeitung zurück",
        "Funktionen können andere Konzepte wie Schleifen und if wiederverwendbar bündeln",
      ],
    },
  ],
  werkstatt: [
    {
      id: "t1p1",
      titel: "Zahlenraten",
      farbe: "var(--cyan)",
      schwierigkeit: 1,
      brief:
        "Baue ein Zahlenraten-Spiel ohne random: Die Geheimzahl ist fest im Code verdrahtet (42). Frage den Nutzer wiederholt per input() nach einer Zahl. Gib nach jedem falschen Versuch 'größer' aus, wenn die Geheimzahl größer als der Tipp ist, sonst 'kleiner'. Sobald der Tipp stimmt, gib 'Richtig! Versuche: <Anzahl>' aus und beende die Schleife. Zähle dafür die Versuche mit.",
      transfer: ["t1l5", "t1l6", "t1l8"],
      starter: "",
      check: {
        stdout: ["größer", "kleiner", "Richtig! Versuche: 3"],
        stdin: ["10", "50", "42"],
      },
      hints: [
        "Nutze eine while True-Schleife, die du mit break verlässt, sobald der Tipp stimmt.",
        "Vergleiche den Tipp mit der festen Geheimzahl über if/elif/else und zähle jeden Versuch mit.",
        "geheimzahl = 42\nversuche = 0\nwhile True:\n    tipp = int(input())\n    versuche = versuche + 1\n    if tipp < geheimzahl:\n        print(\"größer\")\n    elif tipp > geheimzahl:\n        print(\"kleiner\")\n    else:\n        print(f\"Richtig! Versuche: {versuche}\")\n        break",
      ],
      loesung:
        'geheimzahl = 42\nversuche = 0\nwhile True:\n    tipp = int(input())\n    versuche = versuche + 1\n    if tipp < geheimzahl:\n        print("größer")\n    elif tipp > geheimzahl:\n        print("kleiner")\n    else:\n        print(f"Richtig! Versuche: {versuche}")\n        break',
    },
    {
      id: "t1p2",
      titel: "Einkaufslisten-Manager",
      farbe: "var(--teal)",
      schwierigkeit: 2,
      brief:
        "Baue ein Menü-Programm für eine Einkaufsliste. Lies wiederholt per input() einen Befehl ein: 'hinzufuegen', 'anzeigen', 'anzahl' oder 'beenden'. Bei 'hinzufuegen' liest du zusätzlich per input() einen Artikelnamen ein und fügst ihn der Liste hinzu. Bei 'anzeigen' gibst du alle Artikel aus, je einer pro Zeile. Bei 'anzahl' gibst du aus, wie viele Artikel aktuell in der Liste sind. Bei 'beenden' stoppst du die Schleife.",
      transfer: ["t1l7", "t1l8", "t1l6"],
      starter: "",
      check: {
        stdout: ["Milch", "Brot", "2"],
        stdin: ["hinzufuegen", "Milch", "hinzufuegen", "Brot", "anzeigen", "anzahl", "beenden"],
      },
      hints: [
        "Nutze eine while True-Schleife, die auf den Befehl 'beenden' mit break reagiert.",
        "Für jeden Befehl ein eigener elif-Zweig: 'hinzufuegen' liest einen weiteren input() für den Artikel.",
        'liste = []\nwhile True:\n    befehl = input()\n    if befehl == "hinzufuegen":\n        artikel = input()\n        liste.append(artikel)\n    elif befehl == "anzeigen":\n        for artikel in liste:\n            print(artikel)\n    elif befehl == "anzahl":\n        print(len(liste))\n    elif befehl == "beenden":\n        break',
      ],
      loesung:
        'liste = []\nwhile True:\n    befehl = input()\n    if befehl == "hinzufuegen":\n        artikel = input()\n        liste.append(artikel)\n    elif befehl == "anzeigen":\n        for artikel in liste:\n            print(artikel)\n    elif befehl == "anzahl":\n        print(len(liste))\n    elif befehl == "beenden":\n        break',
    },
    {
      id: "t1p3",
      titel: "Noten-Rechner",
      farbe: "var(--gold)",
      schwierigkeit: 2,
      brief:
        "Baue einen Noten-Rechner. Lies wiederholt Punktzahlen (ganze Zahlen) per input() ein, bis der Nutzer 'fertig' eingibt. Berechne danach Durchschnitt, beste und schlechteste Punktzahl per Schleife. Gib Durchschnitt, beste und schlechteste Punktzahl aus (je eine Zeile). Gib zusätzlich einen Notentext aus: 'sehr gut' bei Durchschnitt >= 90, 'gut' bei >= 75, 'befriedigend' bei >= 60, sonst 'nicht bestanden'.",
      transfer: ["t1l1", "t1l2", "t1l3", "t1l5", "t1l6", "t1l7", "t1l8"],
      starter: "",
      check: {
        stdout: ["80.0", "90", "70", "gut"],
        stdin: ["80", "90", "70", "fertig"],
      },
      hints: [
        "Sammle die Punktzahlen in einer Liste, bis die Eingabe 'fertig' ist.",
        "Summiere die Punktzahlen selbst per Schleife (ohne sum()) und teile durch len(punkte) für den Durchschnitt; vergleiche jede Punktzahl mit den bisherigen beste/schlechteste-Werten.",
        "punkte = []\nwhile True:\n    eingabe = input()\n    if eingabe == \"fertig\":\n        break\n    punkte.append(int(eingabe))\n\nsumme = 0\nbeste = punkte[0]\nschlechteste = punkte[0]\nfor p in punkte:\n    summe = summe + p\n    if p > beste:\n        beste = p\n    if p < schlechteste:\n        schlechteste = p\n\ndurchschnitt = summe / len(punkte)\nprint(durchschnitt)\nprint(beste)\nprint(schlechteste)\n\nif durchschnitt >= 90:\n    print(\"sehr gut\")\nelif durchschnitt >= 75:\n    print(\"gut\")\nelif durchschnitt >= 60:\n    print(\"befriedigend\")\nelse:\n    print(\"nicht bestanden\")",
      ],
      loesung:
        'punkte = []\nwhile True:\n    eingabe = input()\n    if eingabe == "fertig":\n        break\n    punkte.append(int(eingabe))\n\nsumme = 0\nbeste = punkte[0]\nschlechteste = punkte[0]\nfor p in punkte:\n    summe = summe + p\n    if p > beste:\n        beste = p\n    if p < schlechteste:\n        schlechteste = p\n\ndurchschnitt = summe / len(punkte)\nprint(durchschnitt)\nprint(beste)\nprint(schlechteste)\n\nif durchschnitt >= 90:\n    print("sehr gut")\nelif durchschnitt >= 75:\n    print("gut")\nelif durchschnitt >= 60:\n    print("befriedigend")\nelse:\n    print("nicht bestanden")',
    },
    {
      id: "t1p4",
      titel: "FizzBuzz deluxe",
      farbe: "var(--blue)",
      schwierigkeit: 2,
      brief:
        "Baue eine Funktion fizzbuzz(obergrenze), die für jede Zahl von 1 bis obergrenze eine Zeile ausgibt: 'Fizz' bei Vielfachen von 3, 'Buzz' bei Vielfachen von 5, 'FizzBuzz' bei Vielfachen von beidem, sonst die Zahl selbst. Rufe die Funktion mit der Obergrenze 15 auf.",
      transfer: ["t1l3", "t1l8", "t1l9"],
      starter: "",
      check: {
        stdout: ["1", "2", "Fizz", "4", "Buzz", "Fizz", "7", "8", "Fizz", "Buzz", "11", "Fizz", "13", "14", "FizzBuzz"],
      },
      hints: [
        "Prüfe zuerst auf Vielfache von 15 (also von 3 UND 5), sonst kommt Fizz oder Buzz nie zum Zug.",
        "for zahl in range(1, obergrenze + 1): mit einer if/elif/elif/else-Kette für 15er-, 3er- und 5er-Vielfache.",
        'def fizzbuzz(obergrenze):\n    for zahl in range(1, obergrenze + 1):\n        if zahl % 15 == 0:\n            print("FizzBuzz")\n        elif zahl % 3 == 0:\n            print("Fizz")\n        elif zahl % 5 == 0:\n            print("Buzz")\n        else:\n            print(zahl)\n\nfizzbuzz(15)',
      ],
      loesung:
        'def fizzbuzz(obergrenze):\n    for zahl in range(1, obergrenze + 1):\n        if zahl % 15 == 0:\n            print("FizzBuzz")\n        elif zahl % 3 == 0:\n            print("Fizz")\n        elif zahl % 5 == 0:\n            print("Buzz")\n        else:\n            print(zahl)\n\nfizzbuzz(15)',
    },
  ],
};
